const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');

const supabase = createClient(
  'https://hbiraafgjshhyjhpbqty.supabase.co',
  process.env.RECETAS_SUPABASE_KEY
);

// ─── 200 UNIQUE MEDITERRANEAN-FUNCTIONAL RECIPE NAMES ───
// All names are unique, evocative, without chef surnames
// Organized by mood (approx 33 per mood to match distribution)

const RECIPES = [
  // ══════ ACTIVACIÓN & ENERGÍA (45) ══════
  { nombre_es: "Tostada de aguacate con huevo pochado, za'atar y limón", nombre_en: "Avocado toast with poached egg, za'atar and lemon", mood_es: "Activación & Energía", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Bowl de quinoa roja con pimiento asado, tahini y granada", nombre_en: "Red quinoa bowl with roasted pepper, tahini and pomegranate", mood_es: "Activación & Energía", tradicion: "Cocina Levantina" },
  { nombre_es: "Revuelto de setas silvestres con trufa y pan de masa madre", nombre_en: "Wild mushroom scramble with truffle and sourdough", mood_es: "Activación & Energía", tradicion: "Alta Cocina Castellana" },
  { nombre_es: "Huevos turcos con yogur especiado y mantequilla de pimentón", nombre_en: "Turkish eggs with spiced yogurt and paprika butter", mood_es: "Activación & Energía", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Tortilla abierta de espárragos verdes con ricotta y menta", nombre_en: "Open asparagus omelette with ricotta and mint", mood_es: "Activación & Energía", tradicion: "Tradición Italiana" },
  { nombre_es: "Gachas de avena con cúrcuma, canela y compota de manzana", nombre_en: "Turmeric cinnamon oatmeal with apple compote", mood_es: "Activación & Energía", tradicion: "Cocina Funcional" },
  { nombre_es: "Shakshuka verde con espinacas, feta y hierbas frescas", nombre_en: "Green shakshuka with spinach, feta and fresh herbs", mood_es: "Activación & Energía", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Bocadillo de pan de centeno con sardinas, tomate y orégano", nombre_en: "Rye bread sandwich with sardines, tomato and oregano", mood_es: "Activación & Energía", tradicion: "Cocina Atlántica" },
  { nombre_es: "Batido espeso de remolacha, jengibre y leche de coco", nombre_en: "Thick beetroot, ginger and coconut milk smoothie", mood_es: "Activación & Energía", tradicion: "Cocina Funcional" },
  { nombre_es: "Wrap de hummus con zanahoria encurtida y rúcula", nombre_en: "Hummus wrap with pickled carrot and arugula", mood_es: "Activación & Energía", tradicion: "Cocina Levantina" },
  { nombre_es: "Tosta de boniato asado con tahini negro y semillas", nombre_en: "Roasted sweet potato toast with black tahini and seeds", mood_es: "Activación & Energía", tradicion: "Cocina Funcional" },
  { nombre_es: "Poke mediterráneo de atún rojo con AOVE y sésamo", nombre_en: "Mediterranean red tuna poke with EVOO and sesame", mood_es: "Activación & Energía", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Migas extremeñas con pimientos del piquillo y uva", nombre_en: "Extremaduran migas with piquillo peppers and grapes", mood_es: "Activación & Energía", tradicion: "Tradición Extremeña" },
  { nombre_es: "Ensalada tibia de lentejas con chorizo ibérico y huevo mollet", nombre_en: "Warm lentil salad with Iberian chorizo and mollet egg", mood_es: "Activación & Energía", tradicion: "Alta Cocina Castellana" },
  { nombre_es: "Crema energizante de calabaza, jengibre y leche de almendra", nombre_en: "Energizing pumpkin cream with ginger and almond milk", mood_es: "Activación & Energía", tradicion: "Cocina Funcional" },
  { nombre_es: "Tabulé de trigo sarraceno con hierbabuena y limón encurtido", nombre_en: "Buckwheat tabbouleh with spearmint and pickled lemon", mood_es: "Activación & Energía", tradicion: "Cocina Levantina" },
  { nombre_es: "Coca de verduras de temporada con romero y flor de sal", nombre_en: "Seasonal vegetable coca with rosemary and fleur de sel", mood_es: "Activación & Energía", tradicion: "Alta Cocina Balear" },
  { nombre_es: "Granola casera de frutos secos con miel de azahar", nombre_en: "Homemade nut granola with orange blossom honey", mood_es: "Activación & Energía", tradicion: "Cocina Funcional" },
  { nombre_es: "Huevos al plato con sobrasada, miel y piñones", nombre_en: "Baked eggs with sobrasada, honey and pine nuts", mood_es: "Activación & Energía", tradicion: "Alta Cocina Balear" },
  { nombre_es: "Zumo prensado de naranja, zanahoria y cúrcuma fresca", nombre_en: "Cold-pressed orange, carrot and fresh turmeric juice", mood_es: "Activación & Energía", tradicion: "Cocina Funcional" },
  { nombre_es: "Pan tumaca con jamón ibérico y tomate de rama", nombre_en: "Tomato bread with Iberian ham and vine tomato", mood_es: "Activación & Energía", tradicion: "Tradición Catalana" },
  { nombre_es: "Empanada gallega de bonito con cebolla caramelizada", nombre_en: "Galician bonito empanada with caramelized onion", mood_es: "Activación & Energía", tradicion: "Cocina Atlántica" },
  { nombre_es: "Tortitas de plátano y avena con frutos rojos naturales", nombre_en: "Banana oat pancakes with natural berries", mood_es: "Activación & Energía", tradicion: "Cocina Funcional" },
  { nombre_es: "Ensalada de garbanzos crujientes con harissa y yogur", nombre_en: "Crispy chickpea salad with harissa and yogurt", mood_es: "Activación & Energía", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Fideuá de verduras con alioli de azafrán", nombre_en: "Vegetable fideuá with saffron aioli", mood_es: "Activación & Energía", tradicion: "Tradición Valenciana" },
  { nombre_es: "Bruschetta de tomate cherry confitado con burrata y albahaca", nombre_en: "Confit cherry tomato bruschetta with burrata and basil", mood_es: "Activación & Energía", tradicion: "Tradición Italiana" },
  { nombre_es: "Arroz integral salteado con verduras de temporada y tamari", nombre_en: "Stir-fried brown rice with seasonal vegetables and tamari", mood_es: "Activación & Energía", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Sopa de tomate asado con pan crujiente y albahaca", nombre_en: "Roasted tomato soup with crispy bread and basil", mood_es: "Activación & Energía", tradicion: "Tradición Italiana" },
  { nombre_es: "Croquetas de jamón ibérico con reducción de Pedro Ximénez", nombre_en: "Iberian ham croquettes with PX reduction", mood_es: "Activación & Energía", tradicion: "Alta Cocina Andaluza" },
  { nombre_es: "Verduras de raíz asadas con miso blanco y sésamo tostado", nombre_en: "Roasted root vegetables with white miso and toasted sesame", mood_es: "Activación & Energía", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Magdalenas de aceite de oliva con ralladura de limón", nombre_en: "Olive oil muffins with lemon zest", mood_es: "Activación & Energía", tradicion: "Repostería Mediterránea" },
  { nombre_es: "Tostas de anchoa del Cantábrico con mantequilla y pimienta", nombre_en: "Cantabrian anchovy toasts with butter and pepper", mood_es: "Activación & Energía", tradicion: "Cocina Atlántica" },
  { nombre_es: "Smoothie bowl de açaí, plátano y manteca de almendra", nombre_en: "Açaí, banana and almond butter smoothie bowl", mood_es: "Activación & Energía", tradicion: "Cocina Funcional" },
  { nombre_es: "Patatas a lo pobre con pimientos confitados y huevo frito", nombre_en: "Poor man's potatoes with confit peppers and fried egg", mood_es: "Activación & Energía", tradicion: "Tradición Andaluza" },
  { nombre_es: "Montadito de salmón ahumado con crema de aguacate y eneldo", nombre_en: "Smoked salmon montadito with avocado cream and dill", mood_es: "Activación & Energía", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Focaccia de tomate seco, aceitunas negras y romero", nombre_en: "Sun-dried tomato, black olive and rosemary focaccia", mood_es: "Activación & Energía", tradicion: "Tradición Italiana" },
  { nombre_es: "Muesli crudo con kéfir, miel y semillas de chía", nombre_en: "Raw muesli with kefir, honey and chia seeds", mood_es: "Activación & Energía", tradicion: "Cocina Funcional" },
  { nombre_es: "Pincho de tortilla española jugosa con cebolla confitada", nombre_en: "Spanish tortilla pintxo with caramelized onion", mood_es: "Activación & Energía", tradicion: "Tradición Vasca" },
  { nombre_es: "Gofre integral con ricotta, miel de romero y nueces", nombre_en: "Whole grain waffle with ricotta, rosemary honey and walnuts", mood_es: "Activación & Energía", tradicion: "Repostería Mediterránea" },
  { nombre_es: "Coca de recapte con escalivada y sardinas", nombre_en: "Empanada-style coca with escalivada and sardines", mood_es: "Activación & Energía", tradicion: "Tradición Catalana" },
  { nombre_es: "Bol de desayuno con labneh, dátiles y pistachos", nombre_en: "Breakfast bowl with labneh, dates and pistachios", mood_es: "Activación & Energía", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Creps de espelta con compota de pera y canela", nombre_en: "Spelt crepes with pear compote and cinnamon", mood_es: "Activación & Energía", tradicion: "Repostería Mediterránea" },
  { nombre_es: "Tostas de pan de pueblo con tomate rallado y AOVE picual", nombre_en: "Village bread toasts with grated tomato and Picual EVOO", mood_es: "Activación & Energía", tradicion: "Tradición Andaluza" },
  { nombre_es: "Ensaladilla rusa moderna con ventresca y mayonesa de yuzu", nombre_en: "Modern Russian salad with tuna belly and yuzu mayo", mood_es: "Activación & Energía", tradicion: "Alta Cocina Vasca" },
  { nombre_es: "Porridge de mijo con mantequilla de cacahuete y plátano", nombre_en: "Millet porridge with peanut butter and banana", mood_es: "Activación & Energía", tradicion: "Cocina Funcional" },

  // ══════ CALMA & EQUILIBRIO (35) ══════
  { nombre_es: "Crema de calabacín con yogur griego y menta fresca", nombre_en: "Courgette cream with Greek yogurt and fresh mint", mood_es: "Calma & Equilibrio", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Sopa miso con tofu sedoso, algas wakame y cebolleta", nombre_en: "Miso soup with silken tofu, wakame and spring onion", mood_es: "Calma & Equilibrio", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Risotto de espárragos verdes con parmesano y limón", nombre_en: "Green asparagus risotto with Parmesan and lemon", mood_es: "Calma & Equilibrio", tradicion: "Tradición Italiana" },
  { nombre_es: "Ensalada templada de judías blancas con cebolla morada y laurel", nombre_en: "Warm white bean salad with red onion and bay leaf", mood_es: "Calma & Equilibrio", tradicion: "Cocina Atlántica" },
  { nombre_es: "Puré de coliflor con AOVE, nuez moscada y cebollino", nombre_en: "Cauliflower purée with EVOO, nutmeg and chives", mood_es: "Calma & Equilibrio", tradicion: "Alta Cocina Castellana" },
  { nombre_es: "Infusión de caldo de pollo con raíz de jengibre y kuzu", nombre_en: "Chicken broth infusion with ginger root and kuzu", mood_es: "Calma & Equilibrio", tradicion: "Cocina Funcional" },
  { nombre_es: "Carpaccio de calabacín con parmesano, menta y piñones", nombre_en: "Courgette carpaccio with Parmesan, mint and pine nuts", mood_es: "Calma & Equilibrio", tradicion: "Tradición Italiana" },
  { nombre_es: "Arroz basmati con cardamomo, pasas y almendras tostadas", nombre_en: "Basmati rice with cardamom, raisins and toasted almonds", mood_es: "Calma & Equilibrio", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Vichyssoise de puerro con aceite de trufa y cebollino", nombre_en: "Leek vichyssoise with truffle oil and chives", mood_es: "Calma & Equilibrio", tradicion: "Alta Cocina Francesa" },
  { nombre_es: "Tataki de atún con vinagreta de soja y jengibre", nombre_en: "Tuna tataki with soy and ginger vinaigrette", mood_es: "Calma & Equilibrio", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Ensalada de hinojo crudo con naranja sanguina y aceitunas", nombre_en: "Raw fennel salad with blood orange and olives", mood_es: "Calma & Equilibrio", tradicion: "Tradición Siciliana" },
  { nombre_es: "Berenjenas asadas con miel de caña y queso de cabra", nombre_en: "Roasted aubergines with cane honey and goat cheese", mood_es: "Calma & Equilibrio", tradicion: "Tradición Andaluza" },
  { nombre_es: "Bowl de arroz integral con edamame, aguacate y sésamo", nombre_en: "Brown rice bowl with edamame, avocado and sesame", mood_es: "Calma & Equilibrio", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Sopa de ajo confitado con huevo escalfado y pan tostado", nombre_en: "Confit garlic soup with poached egg and toast", mood_es: "Calma & Equilibrio", tradicion: "Alta Cocina Castellana" },
  { nombre_es: "Hummus de remolacha con pan pita integral y radishes", nombre_en: "Beetroot hummus with whole wheat pita and radishes", mood_es: "Calma & Equilibrio", tradicion: "Cocina Levantina" },
  { nombre_es: "Fideos de arroz con verduras al wok y salsa de cacahuete", nombre_en: "Rice noodles with wok vegetables and peanut sauce", mood_es: "Calma & Equilibrio", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Alcachofas confitadas en aceite de oliva con tomillo", nombre_en: "Artichokes confit in olive oil with thyme", mood_es: "Calma & Equilibrio", tradicion: "Tradición Provenzal" },
  { nombre_es: "Crema fría de almendras con uva moscatel y aceite verde", nombre_en: "Cold almond cream with muscat grape and green oil", mood_es: "Calma & Equilibrio", tradicion: "Alta Cocina Andaluza" },
  { nombre_es: "Pimientos de padrón con sal Maldon y aceite de sésamo", nombre_en: "Padrón peppers with Maldon salt and sesame oil", mood_es: "Calma & Equilibrio", tradicion: "Cocina Atlántica" },
  { nombre_es: "Ensalada de burrata con melocotón asado y vinagre de Módena", nombre_en: "Burrata salad with roasted peach and Modena vinegar", mood_es: "Calma & Equilibrio", tradicion: "Tradición Italiana" },
  { nombre_es: "Congee de arroz con calabaza y leche de coco", nombre_en: "Rice congee with pumpkin and coconut milk", mood_es: "Calma & Equilibrio", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Gazpacho de cereza con queso fresco y albahaca", nombre_en: "Cherry gazpacho with fresh cheese and basil", mood_es: "Calma & Equilibrio", tradicion: "Alta Cocina Andaluza" },
  { nombre_es: "Tortilla paisana con calabacín, pimiento y cebolla dulce", nombre_en: "Country omelette with courgette, pepper and sweet onion", mood_es: "Calma & Equilibrio", tradicion: "Tradición Española" },
  { nombre_es: "Espárragos blancos con vinagreta de mostaza y huevo picado", nombre_en: "White asparagus with mustard vinaigrette and chopped egg", mood_es: "Calma & Equilibrio", tradicion: "Tradición Navarra" },
  { nombre_es: "Crema de guisantes frescos con hierbabuena y crujiente de jamón", nombre_en: "Fresh pea cream with spearmint and crispy ham", mood_es: "Calma & Equilibrio", tradicion: "Alta Cocina Castellana" },
  { nombre_es: "Tabulé libanés con perejil fresco, tomate y pepino", nombre_en: "Lebanese tabbouleh with fresh parsley, tomato and cucumber", mood_es: "Calma & Equilibrio", tradicion: "Cocina Levantina" },
  { nombre_es: "Menestra de verduras de primavera con jamón y huevo", nombre_en: "Spring vegetable stew with ham and egg", mood_es: "Calma & Equilibrio", tradicion: "Tradición Navarra" },
  { nombre_es: "Ensalada caprese con tomate kumato, mozzarella y albahaca morada", nombre_en: "Caprese salad with kumato tomato, mozzarella and purple basil", mood_es: "Calma & Equilibrio", tradicion: "Tradición Italiana" },
  { nombre_es: "Crema de boniato y zanahoria con jengibre y coco", nombre_en: "Sweet potato and carrot cream with ginger and coconut", mood_es: "Calma & Equilibrio", tradicion: "Cocina Funcional" },
  { nombre_es: "Wonton de seta shiitake en caldo dashi claro", nombre_en: "Shiitake mushroom wonton in clear dashi broth", mood_es: "Calma & Equilibrio", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Ensalada de lentejas negras con queso de cabra y nueces", nombre_en: "Black lentil salad with goat cheese and walnuts", mood_es: "Calma & Equilibrio", tradicion: "Cocina Funcional" },
  { nombre_es: "Tortellini en caldo de parmesano con aceite de trufa", nombre_en: "Tortellini in Parmesan broth with truffle oil", mood_es: "Calma & Equilibrio", tradicion: "Tradición Italiana" },
  { nombre_es: "Tumbet mallorquín con berenjena, patata y pimiento", nombre_en: "Mallorcan tumbet with aubergine, potato and pepper", mood_es: "Calma & Equilibrio", tradicion: "Alta Cocina Balear" },
  { nombre_es: "Leche dorada de cúrcuma con miel y pimienta negra", nombre_en: "Golden turmeric milk with honey and black pepper", mood_es: "Calma & Equilibrio", tradicion: "Cocina Funcional" },
  { nombre_es: "Pisto manchego con huevo escalfado y pan de hogaza", nombre_en: "Manchego ratatouille with poached egg and loaf bread", mood_es: "Calma & Equilibrio", tradicion: "Tradición Castellana" },

  // ══════ FOCUS & CLARIDAD MENTAL (23) ══════
  { nombre_es: "Tartar de salmón con aguacate, soja y aceite de sésamo", nombre_en: "Salmon tartare with avocado, soy and sesame oil", mood_es: "Focus & Claridad Mental", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Ensalada de kale masajeada con nueces, arándanos y parmesano", nombre_en: "Massaged kale salad with walnuts, cranberries and Parmesan", mood_es: "Focus & Claridad Mental", tradicion: "Cocina Funcional" },
  { nombre_es: "Sashimi de lubina con ponzu, rábano y cebolleta", nombre_en: "Sea bass sashimi with ponzu, radish and spring onion", mood_es: "Focus & Claridad Mental", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Bowl de edamame con arroz yaponés y alga nori crujiente", nombre_en: "Edamame bowl with Japanese rice and crispy nori", mood_es: "Focus & Claridad Mental", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Ensalada de espinacas baby con salmón ahumado y alcaparras", nombre_en: "Baby spinach salad with smoked salmon and capers", mood_es: "Focus & Claridad Mental", tradicion: "Cocina Atlántica" },
  { nombre_es: "Crema de brócoli con semillas de calabaza y aceite de nuez", nombre_en: "Broccoli cream with pumpkin seeds and walnut oil", mood_es: "Focus & Claridad Mental", tradicion: "Cocina Funcional" },
  { nombre_es: "Tartar de atún rojo con mango, cilantro y lima", nombre_en: "Red tuna tartare with mango, coriander and lime", mood_es: "Focus & Claridad Mental", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Tosta de sardinas ahumadas con crema de rábano picante", nombre_en: "Smoked sardine toast with horseradish cream", mood_es: "Focus & Claridad Mental", tradicion: "Cocina Atlántica" },
  { nombre_es: "Ensalada de quinoa negra con aguacate, pepino y menta", nombre_en: "Black quinoa salad with avocado, cucumber and mint", mood_es: "Focus & Claridad Mental", tradicion: "Cocina Funcional" },
  { nombre_es: "Caballa en escabeche suave con verduritas crudas", nombre_en: "Gently pickled mackerel with raw baby vegetables", mood_es: "Focus & Claridad Mental", tradicion: "Tradición Española" },
  { nombre_es: "Tazón de matcha latte con leche de avena y cardamomo", nombre_en: "Matcha latte bowl with oat milk and cardamom", mood_es: "Focus & Claridad Mental", tradicion: "Cocina Funcional" },
  { nombre_es: "Ceviche de corvina con leche de tigre y boniato", nombre_en: "Corvina ceviche with tiger's milk and sweet potato", mood_es: "Focus & Claridad Mental", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Ensalada nórdica de arenque con patata, eneldo y mostaza", nombre_en: "Nordic herring salad with potato, dill and mustard", mood_es: "Focus & Claridad Mental", tradicion: "Cocina Atlántica" },
  { nombre_es: "Bowl de açaí con granola, coco rallado y arándanos", nombre_en: "Açaí bowl with granola, shredded coconut and blueberries", mood_es: "Focus & Claridad Mental", tradicion: "Cocina Funcional" },
  { nombre_es: "Tiradito de dorada con ají amarillo y maíz tostado", nombre_en: "Gilt-head bream tiradito with yellow chili and toasted corn", mood_es: "Focus & Claridad Mental", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Ensalada de canónigos con nueces caramelizadas y queso azul", nombre_en: "Lamb's lettuce salad with caramelized walnuts and blue cheese", mood_es: "Focus & Claridad Mental", tradicion: "Alta Cocina Francesa" },
  { nombre_es: "Rollitos de lechuga con gambas, mango y aliño de lima", nombre_en: "Lettuce wraps with prawns, mango and lime dressing", mood_es: "Focus & Claridad Mental", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Crema fría de pepino con yogur, menta y comino tostado", nombre_en: "Cold cucumber cream with yogurt, mint and toasted cumin", mood_es: "Focus & Claridad Mental", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Tosta de aguacate con semillas de cáñamo y rabanitos", nombre_en: "Avocado toast with hemp seeds and radishes", mood_es: "Focus & Claridad Mental", tradicion: "Cocina Funcional" },
  { nombre_es: "Sopa thai de coco con langostinos y hierba limón", nombre_en: "Thai coconut soup with king prawns and lemongrass", mood_es: "Focus & Claridad Mental", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Ensalada de algas con pepino, sésamo y vinagre de arroz", nombre_en: "Seaweed salad with cucumber, sesame and rice vinegar", mood_es: "Focus & Claridad Mental", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Boquerones en vinagre con ajo, perejil y guindilla", nombre_en: "White anchovies in vinegar with garlic, parsley and chili", mood_es: "Focus & Claridad Mental", tradicion: "Tradición Andaluza" },
  { nombre_es: "Bowl proteico de tempeh marinado con boniato y kale", nombre_en: "Marinated tempeh protein bowl with sweet potato and kale", mood_es: "Focus & Claridad Mental", tradicion: "Cocina Funcional" },

  // ══════ SOCIAL & PLACER COMPARTIDO (31) ══════
  { nombre_es: "Tabla de quesos españoles con membrillo y nueces", nombre_en: "Spanish cheese board with quince paste and walnuts", mood_es: "Social & Placer Compartido", tradicion: "Tradición Española" },
  { nombre_es: "Paella de marisco con gambas, mejillones y azafrán", nombre_en: "Seafood paella with prawns, mussels and saffron", mood_es: "Social & Placer Compartido", tradicion: "Tradición Valenciana" },
  { nombre_es: "Croquetas de boletus con trufa y parmesano", nombre_en: "Boletus croquettes with truffle and Parmesan", mood_es: "Social & Placer Compartido", tradicion: "Alta Cocina Castellana" },
  { nombre_es: "Pulpo a la brasa con patata violeta y pimentón de la Vera", nombre_en: "Grilled octopus with purple potato and Vera paprika", mood_es: "Social & Placer Compartido", tradicion: "Cocina Atlántica" },
  { nombre_es: "Gyozas de langostino con salsa ponzu y cebolleta", nombre_en: "King prawn gyoza with ponzu sauce and spring onion", mood_es: "Social & Placer Compartido", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Tartar de tomate rosa con AOVE, alcaparras y miso blanco", nombre_en: "Pink tomato tartare with EVOO, capers and white miso", mood_es: "Social & Placer Compartido", tradicion: "Alta Cocina Española" },
  { nombre_es: "Gambas al ajillo con guindilla y pan crujiente", nombre_en: "Garlic prawns with chili and crispy bread", mood_es: "Social & Placer Compartido", tradicion: "Tradición Española" },
  { nombre_es: "Pizza de masa madre con burrata, tomate cherry y albahaca", nombre_en: "Sourdough pizza with burrata, cherry tomato and basil", mood_es: "Social & Placer Compartido", tradicion: "Tradición Italiana" },
  { nombre_es: "Mejillones al vapor con vino blanco, ajo y perejil", nombre_en: "Steamed mussels with white wine, garlic and parsley", mood_es: "Social & Placer Compartido", tradicion: "Cocina Atlántica" },
  { nombre_es: "Nachos de maíz con guacamole, pico de gallo y crema agria", nombre_en: "Corn nachos with guacamole, pico de gallo and sour cream", mood_es: "Social & Placer Compartido", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Tacos de pescado a la plancha con salsa verde y col morada", nombre_en: "Grilled fish tacos with green sauce and red cabbage", mood_es: "Social & Placer Compartido", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Calamar a la romana con alioli de ajo negro", nombre_en: "Roman-style calamari with black garlic aioli", mood_es: "Social & Placer Compartido", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Patatas bravas con doble salsa: brava y alioli", nombre_en: "Patatas bravas with double sauce: brava and aioli", mood_es: "Social & Placer Compartido", tradicion: "Tradición Española" },
  { nombre_es: "Tabla de ibéricos con pan de cristal y tomate rallado", nombre_en: "Iberian charcuterie board with cristal bread and tomato", mood_es: "Social & Placer Compartido", tradicion: "Tradición Española" },
  { nombre_es: "Brochetas de cordero con salsa de yogur y hierbas", nombre_en: "Lamb skewers with yogurt and herb sauce", mood_es: "Social & Placer Compartido", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Ostras al natural con vinagreta de chalota y limón", nombre_en: "Natural oysters with shallot and lemon vinaigrette", mood_es: "Social & Placer Compartido", tradicion: "Alta Cocina Francesa" },
  { nombre_es: "Queso brie al horno con miel, nueces y romero", nombre_en: "Baked brie with honey, walnuts and rosemary", mood_es: "Social & Placer Compartido", tradicion: "Alta Cocina Francesa" },
  { nombre_es: "Gildas: anchoa, aceituna y guindilla en palillo", nombre_en: "Gildas: anchovy, olive and chili on a stick", mood_es: "Social & Placer Compartido", tradicion: "Tradición Vasca" },
  { nombre_es: "Tataki de ternera con rúcula, parmesano y vinagreta balsámica", nombre_en: "Beef tataki with arugula, Parmesan and balsamic vinaigrette", mood_es: "Social & Placer Compartido", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Txistorra a la parrilla con salsa de mostaza a la antigua", nombre_en: "Grilled txistorra with old-style mustard sauce", mood_es: "Social & Placer Compartido", tradicion: "Tradición Vasca" },
  { nombre_es: "Risotto de setas variadas con aceite de trufa y parmesano", nombre_en: "Mixed mushroom risotto with truffle oil and Parmesan", mood_es: "Social & Placer Compartido", tradicion: "Tradición Italiana" },
  { nombre_es: "Dim sum de langostino con salsa de soja y jengibre", nombre_en: "Prawn dim sum with soy sauce and ginger", mood_es: "Social & Placer Compartido", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Chips de boniato con hummus de aguacate", nombre_en: "Sweet potato chips with avocado hummus", mood_es: "Social & Placer Compartido", tradicion: "Cocina Funcional" },
  { nombre_es: "Carpaccio de ternera con rúcula, alcaparras y parmesano", nombre_en: "Beef carpaccio with arugula, capers and Parmesan", mood_es: "Social & Placer Compartido", tradicion: "Tradición Italiana" },
  { nombre_es: "Pintxo de gamba con reducción de PX y sésamo negro", nombre_en: "Prawn pintxo with PX reduction and black sesame", mood_es: "Social & Placer Compartido", tradicion: "Alta Cocina Vasca" },
  { nombre_es: "Empanadas árabes de carne especiada con yogur", nombre_en: "Spiced meat Arab empanadas with yogurt", mood_es: "Social & Placer Compartido", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Tigres: mejillones rellenos con bechamel y rebozados", nombre_en: "Tigres: breaded stuffed mussels with béchamel", mood_es: "Social & Placer Compartido", tradicion: "Tradición Española" },
  { nombre_es: "Tartaleta de cebolla caramelizada con queso de cabra", nombre_en: "Caramelized onion tartlet with goat cheese", mood_es: "Social & Placer Compartido", tradicion: "Alta Cocina Francesa" },
  { nombre_es: "Spring rolls de vegetales con salsa agridulce casera", nombre_en: "Vegetable spring rolls with homemade sweet and sour sauce", mood_es: "Social & Placer Compartido", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Coca de trampó con pimiento, tomate y cebolla", nombre_en: "Trampó coca with pepper, tomato and onion", mood_es: "Social & Placer Compartido", tradicion: "Alta Cocina Balear" },
  { nombre_es: "Fondue de queso Gruyère con pan, manzana y embutido", nombre_en: "Gruyère cheese fondue with bread, apple and cured meats", mood_es: "Social & Placer Compartido", tradicion: "Alta Cocina Francesa" },

  // ══════ RESET & LIGEREZA (32) ══════
  { nombre_es: "Ensalada de remolacha asada con kéfir de cabra y nuez", nombre_en: "Roasted beetroot salad with goat kefir and walnut", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Sopa fría de pepino fermentado con yogur y eneldo", nombre_en: "Cold fermented cucumber soup with yogurt and dill", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Crudo de lubina con aliño de cítricos y kombucha", nombre_en: "Sea bass crudo with citrus dressing and kombucha", mood_es: "Reset & Ligereza", tradicion: "Alta Cocina Española" },
  { nombre_es: "Carpaccio de rábano con vinagreta de umeboshi y sésamo", nombre_en: "Radish carpaccio with umeboshi vinaigrette and sesame", mood_es: "Reset & Ligereza", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Ensalada detox de col rizada, pepino, apio y manzana verde", nombre_en: "Detox salad with kale, cucumber, celery and green apple", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Gazpacho verde de pepino, manzana y hierbabuena", nombre_en: "Green gazpacho with cucumber, apple and spearmint", mood_es: "Reset & Ligereza", tradicion: "Alta Cocina Andaluza" },
  { nombre_es: "Bowl de kimchi casero con arroz integral y huevo", nombre_en: "Homemade kimchi bowl with brown rice and egg", mood_es: "Reset & Ligereza", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Zumo verde de apio, espinaca, jengibre y limón", nombre_en: "Green juice with celery, spinach, ginger and lemon", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Ensalada de algas hijiki con zanahoria y vinagre de arroz", nombre_en: "Hijiki seaweed salad with carrot and rice vinegar", mood_es: "Reset & Ligereza", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Caldo depurativo de apio, puerro, nabo y cúrcuma", nombre_en: "Cleansing broth with celery, leek, turnip and turmeric", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Tartar vegetal de aguacate, tomate y pepino con lima", nombre_en: "Vegetable tartare with avocado, tomato, cucumber and lime", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Ensalada de sandía con feta, menta y aceite de oliva", nombre_en: "Watermelon salad with feta, mint and olive oil", mood_es: "Reset & Ligereza", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Kombucha de frutos rojos con hielo y hierba luisa", nombre_en: "Berry kombucha with ice and lemon verbena", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Rollitos de pepino con salmón ahumado y queso crema", nombre_en: "Cucumber rolls with smoked salmon and cream cheese", mood_es: "Reset & Ligereza", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Salmorejo cordobés ligero con virutas de jamón", nombre_en: "Light Cordoban salmorejo with ham shavings", mood_es: "Reset & Ligereza", tradicion: "Tradición Andaluza" },
  { nombre_es: "Ensalada de brotes con germinados, semillas y vinagreta cítrica", nombre_en: "Sprout salad with microgreens, seeds and citrus vinaigrette", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Agua de coco con lima, menta y semillas de chía", nombre_en: "Coconut water with lime, mint and chia seeds", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Chucrut casero con salchicha de pollo y mostaza suave", nombre_en: "Homemade sauerkraut with chicken sausage and mild mustard", mood_es: "Reset & Ligereza", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Ensalada de pepino con yogur, ajo y eneldo estilo tzatziki", nombre_en: "Cucumber salad with yogurt, garlic and dill tzatziki-style", mood_es: "Reset & Ligereza", tradicion: "Mediterráneo Oriental" },
  { nombre_es: "Shot de jengibre, limón y cayena para inmunidad", nombre_en: "Ginger, lemon and cayenne immunity shot", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Poke bowl vegano de tofu marinado con mango y aguacate", nombre_en: "Vegan tofu poke bowl with mango and avocado", mood_es: "Reset & Ligereza", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Infusión digestiva de hinojo, anís estrellado y manzanilla", nombre_en: "Digestive infusion of fennel, star anise and chamomile", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Ensalada verde con espárragos, guisantes y vinagreta de mostaza", nombre_en: "Green salad with asparagus, peas and mustard vinaigrette", mood_es: "Reset & Ligereza", tradicion: "Alta Cocina Francesa" },
  { nombre_es: "Smoothie verde de espirulina, piña y leche de coco", nombre_en: "Green spirulina, pineapple and coconut milk smoothie", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Ajoblanco malagueño con uvas y aceite virgen", nombre_en: "Malagan ajoblanco with grapes and virgin oil", mood_es: "Reset & Ligereza", tradicion: "Tradición Andaluza" },
  { nombre_es: "Ensalada thai de papaya verde con cacahuetes y lima", nombre_en: "Thai green papaya salad with peanuts and lime", mood_es: "Reset & Ligereza", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Fermentado de zanahoria y jengibre en tarro", nombre_en: "Carrot and ginger jar ferment", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Bowl de açaí depurativo con semillas y coco rallado", nombre_en: "Cleansing açaí bowl with seeds and shredded coconut", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Pepinos rellenos de atún con aceite de oliva y pimienta rosa", nombre_en: "Tuna-stuffed cucumbers with olive oil and pink pepper", mood_es: "Reset & Ligereza", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Té matcha helado con leche de almendra y vainilla", nombre_en: "Iced matcha tea with almond milk and vanilla", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },
  { nombre_es: "Ceviche de mango y aguacate con cilantro y jalapeño", nombre_en: "Mango and avocado ceviche with coriander and jalapeño", mood_es: "Reset & Ligereza", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Ensalada de frutas tropicales con lima, menta y coco", nombre_en: "Tropical fruit salad with lime, mint and coconut", mood_es: "Reset & Ligereza", tradicion: "Cocina Funcional" },

  // ══════ CONFORT & CALIDEZ (34) ══════
  { nombre_es: "Estofado de ternera con verduras de raíz y romero", nombre_en: "Beef stew with root vegetables and rosemary", mood_es: "Confort & Calidez", tradicion: "Tradición Castellana" },
  { nombre_es: "Mac and cheese con trufa negra y pan rallado crujiente", nombre_en: "Black truffle mac and cheese with crispy breadcrumbs", mood_es: "Confort & Calidez", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Sopa de cebolla gratinada con Gruyère y tomillo", nombre_en: "Gratin onion soup with Gruyère and thyme", mood_es: "Confort & Calidez", tradicion: "Alta Cocina Francesa" },
  { nombre_es: "Lasaña de calabaza y ricotta con salvia y nuez moscada", nombre_en: "Pumpkin and ricotta lasagne with sage and nutmeg", mood_es: "Confort & Calidez", tradicion: "Tradición Italiana" },
  { nombre_es: "Callos a la madrileña con garbanzos y chorizo", nombre_en: "Madrid-style tripe with chickpeas and chorizo", mood_es: "Confort & Calidez", tradicion: "Tradición Castellana" },
  { nombre_es: "Canelones de espinacas y ricotta con bechamel ligera", nombre_en: "Spinach and ricotta cannelloni with light béchamel", mood_es: "Confort & Calidez", tradicion: "Tradición Italiana" },
  { nombre_es: "Cocido madrileño tradicional con tres vuelcos", nombre_en: "Traditional Madrid cocido with three courses", mood_es: "Confort & Calidez", tradicion: "Tradición Castellana" },
  { nombre_es: "Pollo asado con limón, ajo y hierbas provenzales", nombre_en: "Roast chicken with lemon, garlic and Provençal herbs", mood_es: "Confort & Calidez", tradicion: "Tradición Provenzal" },
  { nombre_es: "Albóndigas en salsa de tomate casera con albahaca", nombre_en: "Meatballs in homemade tomato sauce with basil", mood_es: "Confort & Calidez", tradicion: "Tradición Española" },
  { nombre_es: "Lentejas estofadas con verduras, comino y laurel", nombre_en: "Stewed lentils with vegetables, cumin and bay leaf", mood_es: "Confort & Calidez", tradicion: "Tradición Castellana" },
  { nombre_es: "Puré de patata con mantequilla, nuez moscada y cebollino", nombre_en: "Mashed potato with butter, nutmeg and chives", mood_es: "Confort & Calidez", tradicion: "Alta Cocina Francesa" },
  { nombre_es: "Fabada asturiana con compango y azafrán", nombre_en: "Asturian fabada with pork trio and saffron", mood_es: "Confort & Calidez", tradicion: "Tradición Asturiana" },
  { nombre_es: "Arroz meloso de setas de temporada con aceite de trufa", nombre_en: "Creamy seasonal mushroom rice with truffle oil", mood_es: "Confort & Calidez", tradicion: "Alta Cocina Castellana" },
  { nombre_es: "Pasta carbonara con guanciale, pecorino y pimienta negra", nombre_en: "Carbonara pasta with guanciale, pecorino and black pepper", mood_es: "Confort & Calidez", tradicion: "Tradición Italiana" },
  { nombre_es: "Crema de castañas con boletus, trufa y aceite de avellana", nombre_en: "Chestnut cream with boletus, truffle and hazelnut oil", mood_es: "Confort & Calidez", tradicion: "Alta Cocina Castellana" },
  { nombre_es: "Guiso de alubias con almejas y perejil", nombre_en: "Bean and clam stew with parsley", mood_es: "Confort & Calidez", tradicion: "Tradición Vasca" },
  { nombre_es: "Gratén de patata y cebolla con queso Comté", nombre_en: "Potato and onion gratin with Comté cheese", mood_es: "Confort & Calidez", tradicion: "Alta Cocina Francesa" },
  { nombre_es: "Ramen casero de pollo con huevo marinado y nori", nombre_en: "Homemade chicken ramen with marinated egg and nori", mood_es: "Confort & Calidez", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Caldo gallego con grelos, patata y unto", nombre_en: "Galician broth with turnip greens, potato and lard", mood_es: "Confort & Calidez", tradicion: "Cocina Atlántica" },
  { nombre_es: "Pan de banana integral con nueces y canela", nombre_en: "Whole grain banana bread with walnuts and cinnamon", mood_es: "Confort & Calidez", tradicion: "Repostería Mediterránea" },
  { nombre_es: "Curry suave de garbanzos con espinacas y naan", nombre_en: "Mild chickpea and spinach curry with naan", mood_es: "Confort & Calidez", tradicion: "Fusión Mediterránea" },
  { nombre_es: "Sopa de pescado con fideos, azafrán y alioli suave", nombre_en: "Fish soup with noodles, saffron and mild aioli", mood_es: "Confort & Calidez", tradicion: "Tradición Valenciana" },
  { nombre_es: "Arroz con leche cremoso con canela y ralladura de limón", nombre_en: "Creamy rice pudding with cinnamon and lemon zest", mood_es: "Confort & Calidez", tradicion: "Tradición Asturiana" },
  { nombre_es: "Potaje de vigilia con espinacas, bacalao y garbanzos", nombre_en: "Vigil stew with spinach, cod and chickpeas", mood_es: "Confort & Calidez", tradicion: "Tradición Castellana" },
  { nombre_es: "Penne al pesto genovés con piñones y parmesano", nombre_en: "Penne with Genovese pesto, pine nuts and Parmesan", mood_es: "Confort & Calidez", tradicion: "Tradición Italiana" },
  { nombre_es: "Caldo de huesos con verduras aromáticas y colágeno", nombre_en: "Bone broth with aromatic vegetables and collagen", mood_es: "Confort & Calidez", tradicion: "Cocina Funcional" },
  { nombre_es: "Tarta de manzana rústica con masa quebrada y canela", nombre_en: "Rustic apple tart with shortcrust pastry and cinnamon", mood_es: "Confort & Calidez", tradicion: "Repostería Mediterránea" },
  { nombre_es: "Sopa castellana con jamón, pan duro y huevo escalfado", nombre_en: "Castilian soup with ham, stale bread and poached egg", mood_es: "Confort & Calidez", tradicion: "Tradición Castellana" },
  { nombre_es: "Risotto de calabaza con salvia, amaretti y mantequilla", nombre_en: "Pumpkin risotto with sage, amaretti and butter", mood_es: "Confort & Calidez", tradicion: "Tradición Italiana" },
  { nombre_es: "Chocolate caliente espeso con nata montada y canela", nombre_en: "Thick hot chocolate with whipped cream and cinnamon", mood_es: "Confort & Calidez", tradicion: "Tradición Española" },
  { nombre_es: "Macarrones gratinados con ragu de ternera y mozzarella", nombre_en: "Baked macaroni with beef ragù and mozzarella", mood_es: "Confort & Calidez", tradicion: "Tradición Italiana" },
  { nombre_es: "Judiones de la Granja con oreja, morcilla y chorizo", nombre_en: "Granja butter beans with ear, black pudding and chorizo", mood_es: "Confort & Calidez", tradicion: "Tradición Castellana" },
  { nombre_es: "Ñoquis de patata con mantequilla de salvia y parmesano", nombre_en: "Potato gnocchi with sage butter and Parmesan", mood_es: "Confort & Calidez", tradicion: "Tradición Italiana" },
  { nombre_es: "Mugcake de cacao con mantequilla de cacahuete y plátano", nombre_en: "Cocoa mugcake with peanut butter and banana", mood_es: "Confort & Calidez", tradicion: "Repostería Mediterránea" },
];

module.exports = { RECIPES };
