import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })
// Run with: npx ts-node scripts/seed-recetas-funcionales.ts

import { createClient, SupabaseClient } from '@supabase/supabase-js'

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.RECETAS_SUPABASE_KEY

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('❌ Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY')
  process.exit(1)
}

const supabase: SupabaseClient = createClient(SUPABASE_URL, SUPABASE_KEY)

type Ingrediente = { ingrediente: string }
type Paso        = { paso: string }

interface Receta {
  id: string
  nombre_es: string
  mood_es: string
  segmento: string
  sexo: string
  grupo_edad: string
  premium_level: number
  tipo_plato: string
  dificultad: string
  tiempo_preparacion_min: number
  temporada: string
  contexto_es: string
  ingredientes_es: Ingrediente[]
  preparacion_es: Paso[]
  nota_food_mood_es: string
  variantes_es: { variante: string }[]
  tags: string[]
}

// ─────────────────────────────────────────────────────────────────────────────
// 20 RECETAS INTERNACIONALES
// ─────────────────────────────────────────────────────────────────────────────
const INTERNACIONALES: Receta[] = [
  {
    id: 'intl-sopa-miso-fideos-champinones',
    nombre_es: 'Sopa de miso con fideos y champiñones',
    mood_es: 'Calma & Reset',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa', dificultad: 'fácil', tiempo_preparacion_min: 25,
    temporada: 'otoño,invierno',
    contexto_es: 'Ansiedad, agotamiento, necesidad de resetear',
    ingredientes_es: [
      { ingrediente: '1,2 l de caldo de verduras' },
      { ingrediente: '1 puerro' },
      { ingrediente: '1 cebolla' },
      { ingrediente: '3 sobres de fideos udon' },
      { ingrediente: '300 g de champiñones Portobello' },
      { ingrediente: '80 g de cacahuetes tostados' },
      { ingrediente: '1 cucharada sopera de miso' },
      { ingrediente: '1 cucharada de sésamo' },
      { ingrediente: '1 chorro de salsa de soja' },
      { ingrediente: '200 g de tofu firme' },
      { ingrediente: 'cilantro, cebollino, sriracha (opcionales)' },
    ],
    preparacion_es: [
      { paso: 'Calienta el caldo con el puerro y la cebolla picados durante 10 minutos.' },
      { paso: 'Añade los champiñones en láminas y el tofu en dados. Cocina 5 minutos.' },
      { paso: 'Incorpora los fideos udon y cocina según el paquete.' },
      { paso: 'Fuera del fuego, disuelve el miso en un poco de caldo antes de añadirlo.' },
      { paso: 'Sirve con sésamo, cacahuetes, cebollino y sriracha al gusto.' },
    ],
    nota_food_mood_es: 'El miso es un fermentado rico en psicobióticos que modulan el eje intestino-cerebro. El tofu aporta triptófano, precursor de serotonina. Calma reconfortante con base probiótica.',
    variantes_es: [],
    tags: ['calma', 'fermentado', 'miso', 'microbiota', 'sopa', 'internacional', 'umami'],
  },
  {
    id: 'intl-ramen-miso-jengibre-brocoli',
    nombre_es: 'Ramen express con miso, jengibre y brócoli',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa', dificultad: 'fácil', tiempo_preparacion_min: 20,
    temporada: '',
    contexto_es: 'Fatiga mental, bajón de media tarde',
    ingredientes_es: [
      { ingrediente: '150 g de fideos para ramen' },
      { ingrediente: '800 ml de caldo de verduras' },
      { ingrediente: '100 ml de leche de coco' },
      { ingrediente: '2 cucharadas de crema de cacahuete' },
      { ingrediente: '1 cucharadita de miso' },
      { ingrediente: '1 trozo de jengibre fresco (2-3 cm)' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '4 cebolletas chinas' },
      { ingrediente: '1 cucharada de vinagre de arroz' },
      { ingrediente: '1 cucharada de salsa de soja' },
      { ingrediente: '1 cucharada de azúcar' },
      { ingrediente: 'floretes de brócoli, 1 huevo cocido 6-7 min, sésamo' },
    ],
    preparacion_es: [
      { paso: 'Sofríe el ajo y el jengibre rallados en un poco de aceite 2 minutos.' },
      { paso: 'Añade el caldo, la leche de coco, la crema de cacahuete, el vinagre, la soja y el azúcar. Hierve.' },
      { paso: 'Disuelve el miso en el caldo fuera del fuego.' },
      { paso: 'Cuece los fideos aparte. Blanquea el brócoli 2-3 minutos.' },
      { paso: 'Monta el bol: fideos, caldo, brócoli, medio huevo cocido y sésamo.' },
    ],
    nota_food_mood_es: 'El jengibre reduce el cortisol, el miso aporta probióticos y la crema de cacahuete es fuente de triptófano. Energía antiinflamatoria sostenida.',
    variantes_es: [],
    tags: ['activación', 'energía', 'antiinflamatorio', 'ramen', 'miso', 'internacional', 'express'],
  },
  {
    id: 'intl-sopa-miso-setas-huevos-marinados',
    nombre_es: 'Sopa de miso con setas y huevos marinados',
    mood_es: 'Calma & Reset',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '25-65',
    premium_level: 1,
    tipo_plato: 'sopa', dificultad: 'media', tiempo_preparacion_min: 40,
    temporada: 'otoño,invierno',
    contexto_es: 'Melancolía, cambio de estación, soledad',
    ingredientes_es: [
      { ingrediente: '4 huevos medianos' },
      { ingrediente: '50 ml de salsa de soja' },
      { ingrediente: '70 g de miso blanco' },
      { ingrediente: '1 lámina de alga nori' },
      { ingrediente: '200 g de shiitakes frescos' },
      { ingrediente: '200 g de gírgolas (seta ostra)' },
      { ingrediente: '100 g de setas shimeji (o champiñones)' },
      { ingrediente: '1 cebolleta' },
      { ingrediente: '2 l de agua' },
      { ingrediente: '100 g de fideos de arroz' },
    ],
    preparacion_es: [
      { paso: 'Marina los huevos cocidos 6 min en soja diluida con agua, mínimo 2 horas.' },
      { paso: 'Prepara un caldo con el agua, el nori y las setas. Hierve 20 minutos.' },
      { paso: 'Retira el nori. Disuelve el miso fuera del fuego.' },
      { paso: 'Cuece los fideos de arroz aparte.' },
      { paso: 'Sirve con el huevo marinado a la mitad, cebolleta y setas.' },
    ],
    nota_food_mood_es: 'Los shiitakes contienen lentinan inmunomodulador. El miso blanco tiene mayor concentración de GABA natural. Los huevos marinados aportan colina para la memoria. Ritual otoñal reconfortante.',
    variantes_es: [],
    tags: ['calma', 'otoño', 'miso', 'setas', 'fermentado', 'internacional', 'reconfort'],
  },
  {
    id: 'intl-ramen-umami-plant-based',
    nombre_es: 'Ramen Umami Plant-Based con dashi de kombu y shiitake',
    mood_es: 'Foco & Claridad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa', dificultad: 'avanzada', tiempo_preparacion_min: 60,
    temporada: '',
    contexto_es: 'Falta de concentración, necesidad de claridad mental',
    ingredientes_es: [
      { ingrediente: '400 g de fideos para ramen' },
      { ingrediente: '8-10 shiitakes deshidratados' },
      { ingrediente: '20 g de alga kombu' },
      { ingrediente: '1,5 l de agua (para el dashi)' },
      { ingrediente: '90 g de crema de cacahuete' },
      { ingrediente: '110 g de tahini' },
      { ingrediente: '90 g de miso rojo' },
      { ingrediente: '50 g de salsa de soja' },
      { ingrediente: '50 g de doubanjiang' },
      { ingrediente: '30 g de mirin' },
      { ingrediente: '15 g de azúcar moreno' },
      { ingrediente: 'tofu, setas asadas, alga nori, sésamo, cebolleta (toppings)' },
    ],
    preparacion_es: [
      { paso: 'Remoja el kombu y los shiitakes en agua fría 30 minutos. Lleva a ebullición suave y cuela.' },
      { paso: 'Mezcla todos los ingredientes del taré en un bol.' },
      { paso: 'Calienta el dashi y añade el taré al gusto (3-4 cucharadas por bol).' },
      { paso: 'Cuece los fideos aparte. Saltea las setas y el tofu.' },
      { paso: 'Monta: fideos, caldo, toppings al gusto.' },
    ],
    nota_food_mood_es: 'El dashi de kombu aporta glutamato natural (umami) que estimula el sistema de recompensa. El miso rojo tiene mayor concentración de probióticos. El tahini y el cacahuete son fuentes de triptófano y magnesio para el foco sostenido.',
    variantes_es: [],
    tags: ['foco', 'umami', 'plant-based', 'ramen', 'kombu', 'miso', 'internacional', 'neurológico'],
  },
  {
    id: 'intl-chucrut-zanahoria-lactofermentada',
    nombre_es: 'Chucrut y zanahoria lactofermentada caseros',
    mood_es: 'Reset & Microbiota',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'fermentado', dificultad: 'fácil', tiempo_preparacion_min: 30,
    temporada: '',
    contexto_es: 'Quiero cuidar mi microbiota desde casa',
    ingredientes_es: [
      { ingrediente: '1 kg de col blanca' },
      { ingrediente: '15-20 g de sal sin yodo por kg de verdura' },
      { ingrediente: 'semillas de mostaza, pimienta, hinojo o ajo al gusto' },
      { ingrediente: 'para zanahoria: zanahorias + 20 g sal por litro de agua + especias' },
      { ingrediente: 'tarros de cristal con cierre hermético' },
    ],
    preparacion_es: [
      { paso: 'Para el chucrut: corta la col muy fina. Masajea con la sal hasta que suelte líquido (10-15 min).' },
      { paso: 'Añade las especias. Introduce en tarro presionando bien para eliminar burbujas.' },
      { paso: 'Cubre con el líquido generado. Si no es suficiente, añade salmuera al 2%.' },
      { paso: 'Fermenta a temperatura ambiente 1-4 semanas. Prueba a partir del día 7.' },
      { paso: 'Para la zanahoria: corta en bastones, cubre con salmuera al 2%, fermenta 5-7 días.' },
    ],
    nota_food_mood_es: 'Tutorial psicobiótico base de Food-Mood. La fermentación láctica genera Lactobacillus vivos que colonizan el intestino. Una cucharada diaria modula el eje intestino-cerebro. La col fermentada tiene 100x más vitamina C que la fresca.',
    variantes_es: [{ variante: 'Añade remolacha cruda para potenciar el efecto antioxidante con betaína.' }],
    tags: ['reset', 'fermentado', 'microbiota', 'probiótico', 'psicobiótico', 'internacional', 'tutorial'],
  },
  {
    id: 'intl-tartar-salmon-tailandes',
    nombre_es: 'Tartar de salmón al estilo tailandés',
    mood_es: 'Foco & Claridad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '25-65',
    premium_level: 1,
    tipo_plato: 'entrante', dificultad: 'media', tiempo_preparacion_min: 20,
    temporada: 'primavera,verano',
    contexto_es: 'Dispersión, estrés cognitivo',
    ingredientes_es: [
      { ingrediente: '600 g de filete de salmón fresco (sin piel ni espinas)' },
      { ingrediente: '1 cebolleta grande' },
      { ingrediente: '2 limas' },
      { ingrediente: '2 cucharadas de chutney de mango' },
      { ingrediente: '2 cucharadas de salsa de soja' },
      { ingrediente: '1 tacita de cacahuetes tostados pelados' },
      { ingrediente: '2 cucharadas de cilantro picado' },
      { ingrediente: '1 trocito de raíz de jengibre' },
      { ingrediente: '1 cucharada de sésamo' },
      { ingrediente: 'sriracha al gusto' },
      { ingrediente: 'crackers o arroz blanco para acompañar' },
    ],
    preparacion_es: [
      { paso: 'Congela el salmón al menos 48h a -20°C. Descongela en nevera.' },
      { paso: 'Corta en dados pequeños (0,5 cm). Reserva en frío.' },
      { paso: 'Mezcla la lima, soja, chutney de mango y jengibre rallado para la vinagreta.' },
      { paso: 'Marina el salmón 5 minutos. Añade cebolleta y cilantro.' },
      { paso: 'Sirve con sésamo, cacahuetes y sriracha.' },
    ],
    nota_food_mood_es: 'El salmón fresco aporta DHA y EPA esenciales para la función cognitiva y la regulación emocional. El jengibre y el sésamo potencian el efecto antiinflamatorio.',
    variantes_es: [],
    tags: ['foco', 'omega-3', 'salmón', 'claridad', 'internacional', 'entrante'],
  },
  {
    id: 'intl-risotto-caballa-espinacas-limon',
    nombre_es: 'Risotto de caballa y espinacas al limón',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '25-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'media', tiempo_preparacion_min: 35,
    temporada: '',
    contexto_es: 'Agotamiento, falta de vitalidad',
    ingredientes_es: [
      { ingrediente: '2 filetes de caballa a la plancha' },
      { ingrediente: '300 g de arroz arborio' },
      { ingrediente: '300 g de espinacas frescas + perejil' },
      { ingrediente: 'caldo de pescado' },
      { ingrediente: '1 limón (zumo y ralladura)' },
      { ingrediente: '1 puerro' },
      { ingrediente: 'queso parmesano' },
      { ingrediente: 'aceite de oliva virgen extra, sal, pimienta' },
    ],
    preparacion_es: [
      { paso: 'Sofríe el puerro en AOVE a fuego medio 5 minutos.' },
      { paso: 'Añade el arroz y tuesta 2 minutos. Incorpora el caldo cazo a cazo, removiendo.' },
      { paso: 'A media cocción, añade las espinacas troceadas.' },
      { paso: 'Incorpora la caballa desmenuzada, el zumo de limón y el parmesano.' },
      { paso: 'Termina con ralladura de limón y perejil.' },
    ],
    nota_food_mood_es: 'La caballa es uno de los pescados azules más ricos en omega-3 y vitamina D. Con espinacas (magnesio + folatos), este risotto es síntesis pura de neurotransmisores para combatir el agotamiento real.',
    variantes_es: [],
    tags: ['activación', 'omega-3', 'vitamina D', 'espinacas', 'internacional', 'risotto'],
  },
  {
    id: 'intl-pasta-sardinas-pinones',
    nombre_es: 'Pasta con sardinas y piñones',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'fácil', tiempo_preparacion_min: 15,
    temporada: '',
    contexto_es: 'Sin ganas de cocinar pero quiero nutrirme',
    ingredientes_es: [
      { ingrediente: '200 g de pasta (espaguetis o linguini)' },
      { ingrediente: '1 lata de sardinillas en aceite de oliva' },
      { ingrediente: '50 g de piñones' },
      { ingrediente: 'perejil fresco' },
      { ingrediente: 'ajo al gusto' },
      { ingrediente: 'aceite de oliva virgen extra, sal' },
    ],
    preparacion_es: [
      { paso: 'Cuece la pasta. Reserva un vaso del agua de cocción.' },
      { paso: 'Tuesta los piñones en sartén seca. Reserva.' },
      { paso: 'Calienta AOVE con ajo laminado. Añade las sardinas con su aceite.' },
      { paso: 'Incorpora la pasta y el agua de cocción. Mezcla bien.' },
      { paso: 'Sirve con piñones tostados y perejil.' },
    ],
    nota_food_mood_es: 'Las sardinas en lata conservan intactos el DHA y el EPA. Los piñones aportan triptófano y magnesio. 15 minutos para más omega-3 que muchos menús de restaurante.',
    variantes_es: [],
    tags: ['activación', 'omega-3', 'express', 'sardinas', 'internacional', '15 minutos'],
  },
  {
    id: 'intl-bocadillo-arenque-nordico',
    nombre_es: 'Bocadillo de arenque encurtido estilo nórdico',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '25-65',
    premium_level: 1,
    tipo_plato: 'bocadillo', dificultad: 'fácil', tiempo_preparacion_min: 15,
    temporada: '',
    contexto_es: 'Rutina activa, desayuno poderoso',
    ingredientes_es: [
      { ingrediente: '4 filetes de arenque encurtido (o salmón ahumado)' },
      { ingrediente: '2 panecillos tipo hamburguesa o pan de centeno' },
      { ingrediente: '2 hojas de lechuga rizada' },
      { ingrediente: '½ cebolla roja' },
      { ingrediente: '150 g mayonesa' },
      { ingrediente: '1 cucharadita mostaza Dijon' },
      { ingrediente: '1 cucharada alcaparras' },
      { ingrediente: '1 cucharada pepinillos picados' },
      { ingrediente: '2 filetes de anchoa' },
      { ingrediente: 'perejil + ralladura de limón (para la remoulade)' },
    ],
    preparacion_es: [
      { paso: 'Prepara la remoulade mezclando mayonesa, mostaza, alcaparras, pepinillos, anchoa picada, perejil y ralladura de limón.' },
      { paso: 'Tuesta ligeramente el pan.' },
      { paso: 'Monta: pan, remoulade, lechuga, cebolla roja en aros y el arenque.' },
    ],
    nota_food_mood_es: 'El arenque encurtido combina omega-3 con probióticos del encurtido. Las anchoas en la remoulade aportan umami y micronutrientes. Un desayuno nórdico que activa la dopamina y el foco matutino.',
    variantes_es: [{ variante: 'Sustituye el arenque por salmón ahumado para un sabor más suave.' }],
    tags: ['activación', 'omega-3', 'encurtido', 'probiótico', 'internacional', 'nórdico', 'desayuno'],
  },
  {
    id: 'intl-hummus-garbanzos-tahini',
    nombre_es: 'Hummus extrafino de garbanzos con tahini',
    mood_es: 'Calma & Serenidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'dip', dificultad: 'fácil', tiempo_preparacion_min: 10,
    temporada: '',
    contexto_es: 'Ansiedad, picoteo emocional',
    ingredientes_es: [
      { ingrediente: '400 g de garbanzos cocidos (bote)' },
      { ingrediente: '½ cucharadita de comino en grano' },
      { ingrediente: '120-150 g de tahini' },
      { ingrediente: '1 diente de ajo' },
      { ingrediente: '1,5 cucharadas de zumo de limón' },
      { ingrediente: 'sal, cubitos de hielo' },
      { ingrediente: 'AOVE y pimentón para servir' },
    ],
    preparacion_es: [
      { paso: 'Tritura los garbanzos con el tahini, el ajo y el limón.' },
      { paso: 'Añade cubitos de hielo y tritura hasta textura muy fina y cremosa.' },
      { paso: 'Ajusta sal. Si está muy espeso, añade aquafaba (líquido del bote).' },
      { paso: 'Sirve con AOVE y pimentón. Acompaña con crudités o pan de pita.' },
    ],
    nota_food_mood_es: 'Los garbanzos son la fuente vegetal más equilibrada de triptófano + magnesio + inositol. El tahini aporta calcio y lignanos. El hielo crea una emulsión que multiplica la cremosidad. Snack anticiansiedad de alto valor neuronutricional.',
    variantes_es: [
      { variante: 'Añade remolacha cocida para hummus rosa con betaína extra.' },
      { variante: 'Versión verde: añade aguacate o espinacas para más magnesio.' },
    ],
    tags: ['calma', 'triptófano', 'garbanzos', 'tahini', 'snack', 'internacional', 'ansiedad'],
  },
  {
    id: 'intl-hummus-judia-blanca-setas',
    nombre_es: 'Hummus de judía blanca con setas salteadas',
    mood_es: 'Reset & Microbiota',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '25-65',
    premium_level: 1,
    tipo_plato: 'dip', dificultad: 'media', tiempo_preparacion_min: 25,
    temporada: 'otoño,invierno',
    contexto_es: 'Necesito algo diferente, quiero explorar',
    ingredientes_es: [
      { ingrediente: '250 g de judía blanca seca (o 500 g cocida)' },
      { ingrediente: '150 g de tahini' },
      { ingrediente: 'zumo de 1 limón' },
      { ingrediente: '1 diente de ajo' },
      { ingrediente: '100 ml de agua helada' },
      { ingrediente: '200 g de setas (portobello, gírgolas, champiñón)' },
      { ingrediente: '50 g de piñones' },
      { ingrediente: 'sal, pimienta, comino, orégano, perejil fresco' },
    ],
    preparacion_es: [
      { paso: 'Tritura las judías cocidas con el tahini, el ajo, el limón y el agua helada.' },
      { paso: 'Ajusta sal y comino.' },
      { paso: 'Saltea las setas en AOVE a fuego vivo hasta dorar. Añade piñones los últimos 2 min.' },
      { paso: 'Sirve el hummus con setas, piñones, orégano y perejil.' },
    ],
    nota_food_mood_es: 'Las judías blancas tienen mayor concentración de prebióticos que los garbanzos. Las setas aportan betaglucanos inmunomoduladores. Diversificar la microbiota con sabor y elegancia.',
    variantes_es: [],
    tags: ['reset', 'microbiota', 'legumbres', 'setas', 'prebiótico', 'internacional'],
  },
  {
    id: 'intl-espinacas-catalana-garbanzos',
    nombre_es: 'Espinacas a la catalana con garbanzos, piñones y pasas',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'fácil', tiempo_preparacion_min: 20,
    temporada: '',
    contexto_es: 'Cansancio, bajada de hierro, PMS',
    ingredientes_es: [
      { ingrediente: '300 g de espinacas baby' },
      { ingrediente: '800 g de garbanzos cocidos' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '2 cucharadas de piñones tostados' },
      { ingrediente: '2-3 cucharadas de pasas sultanas' },
      { ingrediente: 'aceite de oliva virgen extra, vinagre de Jerez, sal, pimienta' },
    ],
    preparacion_es: [
      { paso: 'Saltea el ajo laminado en AOVE.' },
      { paso: 'Añade los garbanzos y calienta 3 minutos.' },
      { paso: 'Incorpora las espinacas y rehoga hasta que reduzcan.' },
      { paso: 'Añade las pasas y los piñones. Un chorro de vinagre de Jerez al final.' },
    ],
    nota_food_mood_es: 'Espinacas con garbanzos combinan hierro no hemo con vitamina C natural. Los piñones aportan zinc y triptófano. Especialmente útil en la fase premenstrual.',
    variantes_es: [],
    tags: ['activación', 'hierro', 'triptófano', 'espinacas', 'internacional', 'PMS'],
  },
  {
    id: 'intl-ensalada-lentejas-remolacha-manzana',
    nombre_es: 'Ensalada de lentejas con remolacha, manzana y nueces',
    mood_es: 'Reset & Microbiota',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'ensalada', dificultad: 'fácil', tiempo_preparacion_min: 15,
    temporada: 'otoño,invierno',
    contexto_es: 'Reset emocional, necesidad de volver a la normalidad',
    ingredientes_es: [
      { ingrediente: '1 kg de lentejas cocidas' },
      { ingrediente: '500 g de remolachas cocidas' },
      { ingrediente: '2 manzanas' },
      { ingrediente: '1 cebolla roja' },
      { ingrediente: '100 g de nueces' },
      { ingrediente: '50 g de pasas' },
      { ingrediente: '50 g de aceitunas' },
      { ingrediente: 'queso al gusto (feta, manchego…)' },
      { ingrediente: 'aceite de oliva virgen extra, vinagre, sal, pimienta' },
    ],
    preparacion_es: [
      { paso: 'Mezcla las lentejas con la remolacha, la manzana y la cebolla en juliana fina.' },
      { paso: 'Añade las nueces, las pasas y las aceitunas.' },
      { paso: 'Aliña con AOVE, vinagre, sal y pimienta.' },
      { paso: 'Desmenúza el queso por encima al servir.' },
    ],
    nota_food_mood_es: 'La remolacha contiene betaína que apoya la síntesis de dopamina. Las lentejas aportan hierro y triptófano. Las nueces tienen la mayor concentración de omega-3 vegetal (ALA). Un plato de reequilibrio completo.',
    variantes_es: [],
    tags: ['reset', 'microbiota', 'remolacha', 'lentejas', 'omega-3 vegetal', 'internacional', 'ensalada'],
  },
  {
    id: 'intl-guacamole-clasico',
    nombre_es: 'Guacamole clásico y 7 variantes',
    mood_es: 'Foco & Claridad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'dip', dificultad: 'fácil', tiempo_preparacion_min: 10,
    temporada: 'primavera,verano',
    contexto_es: 'Necesito concentrarme, snack consciente',
    ingredientes_es: [
      { ingrediente: '2 aguacates maduros' },
      { ingrediente: 'zumo de 1 lima' },
      { ingrediente: '½ cebolla roja picada' },
      { ingrediente: '2 cucharadas de cilantro fresco' },
      { ingrediente: '1 tomate' },
      { ingrediente: '1 chile serrano' },
      { ingrediente: '1 cucharada de AOVE' },
      { ingrediente: 'sal, pimienta' },
      { ingrediente: 'semillas de granada (variante: polifenoles extra)' },
    ],
    preparacion_es: [
      { paso: 'Aplasta los aguacates con un tenedor. La textura debe ser irregular.' },
      { paso: 'Añade la lima inmediatamente para evitar oxidación.' },
      { paso: 'Incorpora el resto de ingredientes y mezcla.' },
      { paso: 'Ajusta sal. Sirve de inmediato o cubre con film a piel.' },
    ],
    nota_food_mood_es: 'El aguacate es la fuente de grasa monoinsaturada más neuroprotectora. Su ácido oleico forma parte de las membranas neuronales. La luteína del aguacate mejora la cognición. Un snack para el foco real.',
    variantes_es: [
      { variante: 'Con granada: semillas para multiplicar polifenoles y vitamina C.' },
      { variante: 'Con mango: versión tropical con betacarotenos extra.' },
      { variante: 'Con tahini: añade una cucharada para incrementar calcio y sésamo.' },
    ],
    tags: ['foco', 'aguacate', 'grasas saludables', 'snack', 'internacional', 'mexicano'],
  },
  {
    id: 'intl-ensalada-boniato-alubia-aguacate',
    nombre_es: 'Ensalada de boniato, alubias negras y aguacate',
    mood_es: 'Social & Placer',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'ensalada', dificultad: 'fácil', tiempo_preparacion_min: 30,
    temporada: 'otoño,invierno',
    contexto_es: 'Versátil — sirve para varios estados de ánimo',
    ingredientes_es: [
      { ingrediente: '1 boniato grande en dados asados' },
      { ingrediente: '200 g de alubias negras cocidas' },
      { ingrediente: '½ cebolla morada' },
      { ingrediente: 'zumo de lima, chile, AOVE (vinagreta)' },
      { ingrediente: '1 aguacate, lechuga variada, manzana, nueces pecanas (variante)' },
    ],
    preparacion_es: [
      { paso: 'Asa el boniato en dados a 200°C durante 25 minutos.' },
      { paso: 'Monta: boniato asado, alubias negras, cebolla morada en juliana.' },
      { paso: 'Prepara la vinagreta con lima, chile, AOVE, sal.' },
      { paso: 'Aliña y sirve templada.' },
    ],
    nota_food_mood_es: 'El boniato asado tiene índice glucémico menor que la patata hervida. Las alubias negras son la legumbre con mayor concentración de antocianinas neuroprotectoras. El aguacate potencia la absorción de los carotenoides del boniato.',
    variantes_es: [{ variante: 'Añade pollo cocido y nueces pecanas para versión más proteica.' }],
    tags: ['social', 'boniato', 'aguacate', 'alubias', 'ensalada', 'internacional', 'versátil'],
  },
  {
    id: 'intl-bol-avena-platano-cacahuete-cacao',
    nombre_es: 'Bol de avena con plátano, mantequilla de cacahuete y cacao',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'desayuno', dificultad: 'fácil', tiempo_preparacion_min: 10,
    temporada: '',
    contexto_es: 'Mal despertar, necesito empezar bien el día',
    ingredientes_es: [
      { ingrediente: '400 ml de leche (o bebida vegetal)' },
      { ingrediente: '8 cucharadas de copos de avena' },
      { ingrediente: '2 plátanos maduros' },
      { ingrediente: '2 cucharaditas de mantequilla de cacahuete' },
      { ingrediente: 'cacahuetes picados' },
      { ingrediente: 'arándanos frescos' },
      { ingrediente: 'chocolate 70% o pepitas de cacao' },
      { ingrediente: 'canela, AOVE, sal' },
    ],
    preparacion_es: [
      { paso: 'Calienta la leche con los copos de avena removiendo hasta espesar (5 min).' },
      { paso: 'Añade pizca de sal y canela.' },
      { paso: 'Sirve con plátano en rodajas, mantequilla de cacahuete, arándanos, pepitas de cacao y cacahuetes.' },
    ],
    nota_food_mood_es: 'El plátano maduro aporta triptófano + azúcares de absorción progresiva. La mantequilla de cacahuete añade magnesio y proteína. El cacao 70% contiene feniletilamina (euforizante natural). Una serotonina en bol.',
    variantes_es: [],
    tags: ['activación', 'serotonina', 'desayuno', 'avena', 'triptófano', 'internacional'],
  },
  {
    id: 'intl-crema-boniato-coco-jengibre',
    nombre_es: 'Crema de boniato y coco con jengibre',
    mood_es: 'Calma & Serenidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa', dificultad: 'fácil', tiempo_preparacion_min: 30,
    temporada: 'otoño,invierno',
    contexto_es: 'Frío emocional, necesito abrigarme por dentro',
    ingredientes_es: [
      { ingrediente: '800 g de boniatos' },
      { ingrediente: '1 litro de caldo de verduras' },
      { ingrediente: '400 ml de leche de coco' },
      { ingrediente: '1 cucharada de jengibre fresco rallado' },
      { ingrediente: '1 cucharadita de comino' },
      { ingrediente: '1 guindilla o chile rojo' },
      { ingrediente: '1 cucharada de azúcar moreno' },
      { ingrediente: '1 lima' },
      { ingrediente: 'cilantro, aceite, sal' },
    ],
    preparacion_es: [
      { paso: 'Asa los boniatos pelados en dados a 200°C durante 20 minutos.' },
      { paso: 'Sofríe el jengibre, el comino y la guindilla en AOVE 2 minutos.' },
      { paso: 'Añade los boniatos, el caldo y la leche de coco. Hierve 10 minutos.' },
      { paso: 'Tritura hasta textura sedosa. Añade el zumo de lima y el azúcar moreno.' },
      { paso: 'Sirve con cilantro y un chorrito de leche de coco.' },
    ],
    nota_food_mood_es: 'El boniato contiene beta-carotenos y manganeso regulador del ánimo. La leche de coco aporta TCM de absorción rápida para el cerebro. El jengibre bloquea la COX-2, enzima central de la inflamación.',
    variantes_es: [],
    tags: ['calma', 'antiinflamatorio', 'boniato', 'jengibre', 'coco', 'internacional', 'sopa'],
  },
  {
    id: 'intl-crema-alubias-negras-mexicana',
    nombre_es: 'Crema de alubias negras tipo mexicana',
    mood_es: 'Confort & Reconfort',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa', dificultad: 'fácil', tiempo_preparacion_min: 25,
    temporada: 'otoño,invierno',
    contexto_es: 'Tristeza, necesidad de reconforto profundo',
    ingredientes_es: [
      { ingrediente: '400 g de alubias negras cocidas' },
      { ingrediente: '600 ml de caldo de verduras' },
      { ingrediente: '1 cebolla, 1 zanahoria, 1 guindilla' },
      { ingrediente: '1 cucharadita de comino' },
      { ingrediente: '1 lima' },
      { ingrediente: '1 aguacate (para servir)' },
      { ingrediente: '1 tomate picado' },
      { ingrediente: 'AOVE, sal' },
    ],
    preparacion_es: [
      { paso: 'Sofríe la cebolla y la zanahoria en dados 8 minutos. Añade el comino y la guindilla.' },
      { paso: 'Incorpora las alubias y el caldo. Hierve 10 minutos.' },
      { paso: 'Tritura la mitad para textura cremosa con tropezones.' },
      { paso: 'Sirve con aguacate en láminas, tomate fresco y lima.' },
    ],
    nota_food_mood_es: 'Las alubias negras contienen antocianinas neuroprotectoras. La combinación caldo + legumbre + aguacate crea saciedad sostenida y estabilidad glucémica que previene los bajones de ánimo.',
    variantes_es: [],
    tags: ['confort', 'alubias', 'antocianinas', 'prebiótico', 'internacional', 'mexicano', 'sopa'],
  },
  {
    id: 'intl-sopa-verduras-invierno-fideos',
    nombre_es: 'Sopa de verduras de invierno con fideos integrales y huevo',
    mood_es: 'Reset & Microbiota',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa', dificultad: 'fácil', tiempo_preparacion_min: 35,
    temporada: 'invierno',
    contexto_es: 'Después de excesos, quiero volver al equilibrio',
    ingredientes_es: [
      { ingrediente: '4 zanahorias grandes' },
      { ingrediente: '2 puerros' },
      { ingrediente: '1 nabo mediano' },
      { ingrediente: '300 g de espinacas frescas' },
      { ingrediente: '200 g de fideos integrales' },
      { ingrediente: '8 huevos' },
      { ingrediente: '2 l de caldo de verduras' },
      { ingrediente: 'AOVE, sal, pimienta, limón' },
    ],
    preparacion_es: [
      { paso: 'Lleva el caldo a ebullición. Añade las zanahorias, el puerro y el nabo en dados 15 minutos.' },
      { paso: 'Incorpora los fideos integrales y cocina según el paquete.' },
      { paso: 'Añade las espinacas los últimos 2 minutos.' },
      { paso: 'Cuece los huevos aparte (6-7 min para yema cremosa). Sirve con medio huevo por bol.' },
      { paso: 'Termina con AOVE, pimienta y zumo de limón.' },
    ],
    nota_food_mood_es: 'Los fideos integrales tienen índice glucémico 30% menor que los refinados. Verduras de raíz + espinacas + huevo cubren los principales micronutrientes del eje intestino-cerebro. Un reset real, no una restricción.',
    variantes_es: [],
    tags: ['reset', 'detox', 'invierno', 'verduras', 'internacional', 'sopa', 'reconfort'],
  },
  {
    id: 'intl-tortitas-platano-avena-chia',
    nombre_es: 'Tortitas de plátano, avena y chía',
    mood_es: 'Social & Placer',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'desayuno', dificultad: 'fácil', tiempo_preparacion_min: 20,
    temporada: '',
    contexto_es: 'Celebración tranquila, autocuidado del fin de semana',
    ingredientes_es: [
      { ingrediente: '3 plátanos grandes maduros' },
      { ingrediente: '75 g de copos de avena integrales' },
      { ingrediente: '200 ml de leche o bebida vegetal' },
      { ingrediente: '1 cucharada de semillas de chía' },
      { ingrediente: '13 g de impulsor (levadura tipo Royal)' },
      { ingrediente: 'aceite neutro' },
      { ingrediente: 'arándanos, pepitas de cacao, miel, frutos rojos (toppings)' },
    ],
    preparacion_es: [
      { paso: 'Tritura los plátanos con la leche.' },
      { paso: 'Añade los copos de avena, la chía y el impulsor. Reposa 5 minutos.' },
      { paso: 'Cocina en sartén antiadherente, fuego medio-bajo, 2-3 min por lado.' },
      { paso: 'Sirve con arándanos, pepitas de cacao y un hilo de miel.' },
    ],
    nota_food_mood_es: 'El plátano maduro tiene prebióticos + triptófano + magnesio. La chía aporta omega-3 vegetal (ALA). La avena tiene avenantramidas con efecto ansiolítico. El ritual del fin de semana que nutre el sistema nervioso.',
    variantes_es: [],
    tags: ['social', 'placer', 'desayuno', 'triptófano', 'omega-3 vegetal', 'internacional', 'fin de semana'],
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// 20 RECETAS ESPAÑOLAS
// ─────────────────────────────────────────────────────────────────────────────
const ESPANOLAS: Receta[] = [
  {
    id: 'esp-gazpacho-antiguo',
    nombre_es: '🇪🇸 Gazpacho a la antigua',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa fría', dificultad: 'fácil', tiempo_preparacion_min: 15,
    temporada: 'verano',
    contexto_es: 'Agotamiento por calor, necesito hidratarme y recargar',
    ingredientes_es: [
      { ingrediente: '½ kg de tomates de temporada maduros' },
      { ingrediente: '1 pepino pequeño' },
      { ingrediente: '½ cebolla' },
      { ingrediente: '1 diente de ajo' },
      { ingrediente: 'media barra de pan candeal del día anterior' },
      { ingrediente: '50-60 ml de aceite de oliva virgen extra (AOVE)' },
      { ingrediente: 'chorretón de vinagre de Jerez' },
      { ingrediente: '1 l de agua fresca' },
      { ingrediente: 'hierbas aromáticas frescas (albahaca, tomillo, salvia)' },
      { ingrediente: 'sal' },
    ],
    preparacion_es: [
      { paso: 'Tritura los tomates, el pepino, la cebolla y el ajo con el pan remojado.' },
      { paso: 'Añade el AOVE en hilo mientras trituras para emulsionar.' },
      { paso: 'Incorpora el vinagre de Jerez y el agua fría hasta la textura deseada.' },
      { paso: 'Sazona y enfría mínimo 2 horas. Sirve con hierbas frescas.' },
    ],
    nota_food_mood_es: 'Tradición + Función. El tomate maduro de temporada contiene hasta 5x más licopeno que el de invernadero. El AOVE potencia su absorción (liposoluble). El vinagre de Jerez regula la glucemia postprandial. El gazpacho es medicina funcional andaluza.',
    variantes_es: [{ variante: 'Gazpacho de remolacha: añade 1 remolacha cocida para multiplicar los nitratos vasodilatadores.' }],
    tags: ['activación', 'licopeno', 'antioxidante', 'española', 'verano', 'sopa fría', 'dieta mediterránea', 'andalucía'],
  },
  {
    id: 'esp-salmorejo-cordob',
    nombre_es: '🇪🇸 Salmorejo cordobés',
    mood_es: 'Calma & Serenidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa fría', dificultad: 'fácil', tiempo_preparacion_min: 15,
    temporada: 'primavera,verano',
    contexto_es: 'Estrés, necesito algo denso y saciante sin pesadez',
    ingredientes_es: [
      { ingrediente: '500 g de tomates maduros' },
      { ingrediente: '300 g de miga de pan del día anterior' },
      { ingrediente: '125 ml de AOVE' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '2 huevos (para decorar)' },
      { ingrediente: 'sal, vinagre' },
      { ingrediente: 'jamón ibérico en taquitos (opcional)' },
    ],
    preparacion_es: [
      { paso: 'Tritura los tomates con el pan remojado y el ajo.' },
      { paso: 'Añade el AOVE en hilo sin dejar de triturar hasta emulsionar.' },
      { paso: 'Ajusta sal y vinagre. La textura debe ser densa y cremosa.' },
      { paso: 'Enfría mínimo 1 hora. Sirve con huevo duro rallado y jamón ibérico.' },
    ],
    nota_food_mood_es: 'Tradición + Función. El salmorejo concentra más licopeno que el gazpacho gracias a la emulsión con AOVE. El pan de masa madre fermentada añade probióticos. Carotenoides que protegen el sistema nervioso del estrés oxidativo.',
    variantes_es: [],
    tags: ['calma', 'licopeno', 'española', 'verano', 'sopa fría', 'córdoba', 'dieta mediterránea'],
  },
  {
    id: 'esp-ajoblanco-pepino-almendras',
    nombre_es: '🇪🇸 Ajoblanco de pepino y almendras',
    mood_es: 'Foco & Claridad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa fría', dificultad: 'fácil', tiempo_preparacion_min: 15,
    temporada: 'verano',
    contexto_es: 'Calor y niebla mental, necesito refrescar la cabeza',
    ingredientes_es: [
      { ingrediente: '100 g de almendras crudas' },
      { ingrediente: '50 g de almendras tostadas' },
      { ingrediente: '150 g de miga de pan' },
      { ingrediente: '500 g de pepino' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '50 ml de vinagre de vino blanco' },
      { ingrediente: '100 ml de AOVE' },
      { ingrediente: '500 ml de agua fría' },
      { ingrediente: 'sal, cebollino picado' },
    ],
    preparacion_es: [
      { paso: 'Remoja las almendras crudas 4 horas o toda la noche.' },
      { paso: 'Tritura las almendras con el pan remojado, el pepino, el ajo y el vinagre.' },
      { paso: 'Añade el AOVE en hilo y el agua fría hasta textura cremosa.' },
      { paso: 'Ajusta sal. Sirve muy frío con cebollino y uvas blancas.' },
    ],
    nota_food_mood_es: 'Tradición + Función. Las almendras son la fuente más concentrada de vitamina E (antioxidante neuronal) y magnesio en la cocina mediterránea. El pepino hidrata con silicio para la síntesis de colágeno. El ajoblanco es el nootropic andaluz.',
    variantes_es: [{ variante: 'Añade uvas blancas congeladas como tropezón para más resveratrol.' }],
    tags: ['foco', 'vitamina E', 'almendras', 'española', 'verano', 'sopa fría', 'andalucía', 'dieta mediterránea'],
  },
  {
    id: 'esp-mazamorra-cordobesa',
    nombre_es: '🇪🇸 Mazamorra cordobesa',
    mood_es: 'Calma & Serenidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa fría', dificultad: 'fácil', tiempo_preparacion_min: 15,
    temporada: 'verano',
    contexto_es: 'Hambre emocional, necesito algo contundente y nutritivo',
    ingredientes_es: [
      { ingrediente: '100 g de almendra cruda' },
      { ingrediente: '75 g de almendra tostada' },
      { ingrediente: '75 g de almendra frita' },
      { ingrediente: '150 g de miga de pan tipo telera' },
      { ingrediente: '2 dientes de ajo (sin germen)' },
      { ingrediente: 'AOVE al gusto' },
      { ingrediente: 'vinagre de Jerez' },
      { ingrediente: 'sal, agua fría' },
    ],
    preparacion_es: [
      { paso: 'Tritura las tres variedades de almendra con el pan remojado y el ajo.' },
      { paso: 'Añade el AOVE y el vinagre. Tritura añadiendo agua fría hasta la textura deseada.' },
      { paso: 'Ajusta sal. Sirve muy frío, opcionalmente con miel y uvas.' },
    ],
    nota_food_mood_es: 'Tradición + Función. La mazamorra es el antepasado del salmorejo: almendras, pan, ajo y aceite. Tres tipos de almendra crean perfiles distintos de vitamina E y magnesio. La saciedad que genera es profunda y estable.',
    variantes_es: [],
    tags: ['calma', 'almendras', 'española', 'verano', 'sopa fría', 'córdoba', 'saciedad', 'dieta mediterránea'],
  },
  {
    id: 'esp-alboronia-pisto-original',
    nombre_es: '🇪🇸 Alboronía (la madre del pisto)',
    mood_es: 'Confort & Reconfort',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'fácil', tiempo_preparacion_min: 45,
    temporada: 'verano,otoño',
    contexto_es: 'Nostalgia, necesidad de conectar con lo esencial',
    ingredientes_es: [
      { ingrediente: '500 g de calabaza pelada' },
      { ingrediente: '4 berenjenas' },
      { ingrediente: '1 calabacín' },
      { ingrediente: '1 pimiento verde' },
      { ingrediente: '2 cebollas' },
      { ingrediente: '3 dientes de ajo' },
      { ingrediente: '500 g de tomates' },
      { ingrediente: '1 cucharadita de pimentón dulce' },
      { ingrediente: '1 cucharadita de vinagre' },
      { ingrediente: 'AOVE, sal' },
    ],
    preparacion_es: [
      { paso: 'Corta todas las verduras en dados irregulares.' },
      { paso: 'Sofríe la cebolla y el ajo en AOVE generoso hasta pochar (10 min).' },
      { paso: 'Añade el pimiento, la berenjena y el calabacín. Tapa 15 minutos.' },
      { paso: 'Incorpora la calabaza, el tomate y el pimentón. Cocina otros 20 minutos.' },
      { paso: 'Añade el vinagre al final para equilibrar.' },
    ],
    nota_food_mood_es: 'Tradición + Función. La alboronía es la receta de pisto más antigua de la Península (origen árabe-andalusí). La berenjena contiene nasunina que protege las membranas cerebrales. La calabaza aporta zinc y triptófano. Raíces que nutren.',
    variantes_es: [],
    tags: ['confort', 'arraigo', 'berenjena', 'prebiótico', 'española', 'andalucía', 'tradición', 'dieta mediterránea'],
  },
  {
    id: 'esp-escalivada-horno',
    nombre_es: '🇪🇸 Escalivada al horno',
    mood_es: 'Calma & Serenidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'fácil', tiempo_preparacion_min: 60,
    temporada: 'verano,otoño',
    contexto_es: 'Estrés crónico, necesito simplicidad y sabor',
    ingredientes_es: [
      { ingrediente: '4 berenjenas' },
      { ingrediente: '4 pimientos rojos' },
      { ingrediente: '3 cebollas' },
      { ingrediente: 'AOVE, sal, pimienta' },
      { ingrediente: 'opcionales: patatas, tomates, vinagre, ajo, perejil' },
    ],
    preparacion_es: [
      { paso: 'Pon las verduras enteras en bandeja. Pincela con AOVE.' },
      { paso: 'Hornea a 200°C durante 45-55 minutos, girando a mitad.' },
      { paso: 'Cubre con papel de aluminio 15 minutos para que suden.' },
      { paso: 'Pela las verduras. Corta en tiras y aliña con AOVE, sal y vinagre.' },
    ],
    nota_food_mood_es: 'Tradición + Función. El asado concentra los carotenoides del pimiento rojo (capsantina, betacaroteno) y los hace más biodisponibles. El AOVE al servir potencia su absorción. La berenjena asada es más digestiva que la cruda. Serenidad que se hornea.',
    variantes_es: [],
    tags: ['calma', 'antioxidante', 'española', 'cataluña', 'asado', 'dieta mediterránea'],
  },
  {
    id: 'esp-menestra-primavera-salsa-tartara',
    nombre_es: '🇪🇸 Menestra de primavera con salsa tártara',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'media', tiempo_preparacion_min: 30,
    temporada: 'primavera',
    contexto_es: 'Renovación, quiero ligereza después del invierno',
    ingredientes_es: [
      { ingrediente: '3 alcachofas' },
      { ingrediente: '50 g de espárragos verdes' },
      { ingrediente: '3 espárragos blancos frescos' },
      { ingrediente: '50 g de guisantes frescos' },
      { ingrediente: '50 g de tirabeques' },
      { ingrediente: '50 g de judías verdes' },
      { ingrediente: 'mantequilla + AOVE, sal' },
      { ingrediente: '150 g mayonesa, mostaza Dijon, pepinillos, alcaparras, aceitunas, eneldo, cebollino (salsa tártara)' },
    ],
    preparacion_es: [
      { paso: 'Limpia y cuece cada verdura por separado al dente.' },
      { paso: 'Saltea en mantequilla y AOVE unos minutos.' },
      { paso: 'Prepara la tártara mezclando todos los ingredientes finamente picados.' },
      { paso: 'Sirve la menestra con la salsa en el lado.' },
    ],
    nota_food_mood_es: 'Tradición + Función. Las alcachofas contienen cinarina que estimula la bilis y apoya el metabolismo hormonal. Los guisantes y espárragos combinan folatos + triptófano: síntesis de serotonina de primavera.',
    variantes_es: [],
    tags: ['activación', 'primavera', 'alcachofas', 'española', 'verduras', 'folatos', 'dieta mediterránea'],
  },
  {
    id: 'esp-huevos-al-plato-hojas-verdes',
    nombre_es: '🇪🇸 Huevos al plato de hojas verdes',
    mood_es: 'Confort & Reconfort',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'fácil', tiempo_preparacion_min: 25,
    temporada: '',
    contexto_es: 'Agotamiento, necesito nutrirme sin esfuerzo',
    ingredientes_es: [
      { ingrediente: '4 huevos' },
      { ingrediente: '1 puerro' },
      { ingrediente: '3 hojas grandes de acelga' },
      { ingrediente: '200 g de espinacas' },
      { ingrediente: '5 ajetes tiernos' },
      { ingrediente: '150 ml de nata' },
      { ingrediente: '50 g de queso curado rallado' },
      { ingrediente: '3 cucharadas de pesto' },
      { ingrediente: 'AOVE, sal, pimienta negra' },
    ],
    preparacion_es: [
      { paso: 'Sofríe el puerro y los ajetes en AOVE hasta pochar.' },
      { paso: 'Añade las acelgas y las espinacas. Rehoga hasta que reduzcan.' },
      { paso: 'Vierte la nata y el pesto. Cocina a fuego suave 2 minutos.' },
      { paso: 'Haz huecos y casca los huevos dentro.' },
      { paso: 'Cubre con queso rallado y hornea a 180°C hasta que la clara cuaje (8-10 min).' },
    ],
    nota_food_mood_es: 'Tradición + Función. Los huevos al plato combinan colina (memoria), vitamina D (ánimo) y proteína completa. Las espinacas y acelgas añaden magnesio y folatos. El pesto aporta albahaca con linalool ansiolítico.',
    variantes_es: [],
    tags: ['confort', 'magnesio', 'española', 'huevos', 'folatos', 'reconfort', 'fácil'],
  },
  {
    id: 'esp-bonito-encebollado',
    nombre_es: '🇪🇸 Bonito encebollado tradicional',
    mood_es: 'Confort & Reconfort',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '25-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'media', tiempo_preparacion_min: 50,
    temporada: 'verano',
    contexto_es: 'Melancolía, quiero algo reconfortante con raíces',
    ingredientes_es: [
      { ingrediente: '750 g de bonito del norte limpio' },
      { ingrediente: '4 cebollas dulces' },
      { ingrediente: '2 pimientos verdes italianos' },
      { ingrediente: '3 dientes de ajo' },
      { ingrediente: '100 ml de fumet de pescado' },
      { ingrediente: '100 ml de vino blanco seco' },
      { ingrediente: '1 hoja de laurel' },
      { ingrediente: '100 g de AOVE, sal' },
    ],
    preparacion_es: [
      { paso: 'Pocha la cebolla en juliana en AOVE generoso a fuego muy lento, 30-40 min.' },
      { paso: 'Añade el pimiento y el ajo. Cocina 10 minutos.' },
      { paso: 'Incorpora el vino y el fumet. Reduce a la mitad.' },
      { paso: 'Añade el bonito en tacos y cocina 5-7 minutos. El interior debe quedar rosado.' },
    ],
    nota_food_mood_es: 'Tradición + Función. El bonito del norte tiene los mismos omega-3 (EPA + DHA) que los antidepresivos de baja intensidad según estudios recientes. La cebolla confitada aporta quercetina antiinflamatoria. Raíces que sanan.',
    variantes_es: [],
    tags: ['confort', 'omega-3', 'española', 'cantábrico', 'pescado azul', 'tradición', 'dieta mediterránea'],
  },
  {
    id: 'esp-boquerones-vinagre-arroz',
    nombre_es: '🇪🇸 Boquerones en vinagre de arroz con chalota',
    mood_es: 'Reset & Microbiota',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'entrante', dificultad: 'media', tiempo_preparacion_min: 30,
    temporada: 'verano',
    contexto_es: 'Aperitivo consciente, cuidar la microbiota de forma sabrosa',
    ingredientes_es: [
      { ingrediente: '1 kg de boquerones limpios (sin espinas ni cabeza)' },
      { ingrediente: 'sal, vinagre de arroz' },
      { ingrediente: 'AOVE' },
      { ingrediente: '8 chalotas' },
      { ingrediente: '250 ml de aceite con 1 cucharadita de pimentón' },
      { ingrediente: 'perejil fresco' },
      { ingrediente: 'salsa de soja' },
    ],
    preparacion_es: [
      { paso: 'Congela los boquerones 48h a -20°C. Descongela en nevera.' },
      { paso: 'Marina en sal y vinagre de arroz 2-4 horas hasta que la carne se ponga blanca.' },
      { paso: 'Escurre y cubre con AOVE infusionado con pimentón.' },
      { paso: 'Sirve con chalotas en láminas, perejil y gotas de salsa de soja.' },
    ],
    nota_food_mood_es: 'Tradición + Función. Los boquerones en vinagre combinan omega-3 con ácido acético que regula la glucemia y tiene efecto prebiótico. El vinagre de arroz es más suave que el de manzana. Una tapa que cuida el eje intestino-cerebro sin saberlo.',
    variantes_es: [],
    tags: ['reset', 'omega-3', 'encurtido', 'española', 'microbiota', 'boquerones', 'dieta mediterránea'],
  },
  {
    id: 'esp-mejillones-vapor-jengibre-chile',
    nombre_es: '🇪🇸 Mejillones al vapor con jengibre, limón y chile',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'entrante', dificultad: 'fácil', tiempo_preparacion_min: 10,
    temporada: 'otoño,invierno',
    contexto_es: 'Bajón de energía, necesito minerales y sabor en 10 minutos',
    ingredientes_es: [
      { ingrediente: '1 kg de mejillones frescos' },
      { ingrediente: '2 cm de raíz de jengibre fresco' },
      { ingrediente: '1 limón' },
      { ingrediente: '10 vainas de cebollino' },
      { ingrediente: '1 cucharadita de chile en copos' },
    ],
    preparacion_es: [
      { paso: 'Limpia los mejillones desechando los que estén abiertos.' },
      { paso: 'Calienta una cazuela alta a fuego vivo con un chorro de agua o vino blanco.' },
      { paso: 'Introduce los mejillones, tapa y cocina 3-4 minutos hasta que se abran.' },
      { paso: 'Descarta los que no se hayan abierto. Sirve con jengibre rallado, lima, chile y cebollino.' },
    ],
    nota_food_mood_es: 'Tradición + Función. Los mejillones son el alimento más rico en zinc, yodo y vitamina B12 del mar. El zinc es esencial para la función inmune y la síntesis de testosterona. El B12 forma la mielina. 10 minutos para una batería de minerales marinos.',
    variantes_es: [],
    tags: ['activación', 'zinc', 'yodo', 'B12', 'española', 'mariscos', 'minerales', 'express'],
  },
  {
    id: 'esp-ensalada-malaguena-naranja-bacalao',
    nombre_es: '🇪🇸 Ensalada malagueña de naranja y bacalao',
    mood_es: 'Reset & Microbiota',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '25-65',
    premium_level: 1,
    tipo_plato: 'ensalada', dificultad: 'fácil', tiempo_preparacion_min: 20,
    temporada: 'invierno',
    contexto_es: 'Necesito ligereza, algo fresco y con historia',
    ingredientes_es: [
      { ingrediente: '300 g de bacalao desalado' },
      { ingrediente: '400 g de patata roja' },
      { ingrediente: '400 g de batata' },
      { ingrediente: '3 cebolletas picadas' },
      { ingrediente: '2 naranjas' },
      { ingrediente: '15 aceitunas verdes tipo aloreña' },
      { ingrediente: 'perejil picado' },
      { ingrediente: '4 cucharadas de AOVE' },
      { ingrediente: 'vinagre de Jerez, sal' },
    ],
    preparacion_es: [
      { paso: 'Cuece las patatas y la batata con piel. Pela y trocea.' },
      { paso: 'Desmiga el bacalao desalado en lascas.' },
      { paso: 'Pela las naranjas a vivo y corta en gajos.' },
      { paso: 'Monta: tubérculos, bacalao, naranja, cebolleta y aceitunas.' },
      { paso: 'Aliña con AOVE, vinagre de Jerez, sal y perejil.' },
    ],
    nota_food_mood_es: 'Tradición + Función. El bacalao (proteína + omega-3 + vitamina D) con la naranja (vitamina C que potencia la absorción del hierro del perejil). Las aceitunas aloreñas son fermentadas: probiótico andaluz milenario.',
    variantes_es: [],
    tags: ['reset', 'omega-3', 'vitamina C', 'española', 'málaga', 'bacalao', 'ensalada', 'dieta mediterránea'],
  },
  {
    id: 'esp-lentejas-pardinas-infalibles',
    nombre_es: '🇪🇸 Lentejas pardinas infalibles',
    mood_es: 'Calma & Serenidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'fácil', tiempo_preparacion_min: 50,
    temporada: 'otoño,invierno',
    contexto_es: 'Inestabilidad emocional, necesito un plato que me ancle',
    ingredientes_es: [
      { ingrediente: '400 g de lentejas pardinas' },
      { ingrediente: '1 patata grande (o 2 pequeñas)' },
      { ingrediente: '2 zanahorias' },
      { ingrediente: '1 cebolla grande' },
      { ingrediente: '1 diente de ajo' },
      { ingrediente: '4 cucharadas de tomate triturado' },
      { ingrediente: '¼ pimiento rojo o ½ verde' },
      { ingrediente: '1 cucharadita de pimentón ahumado' },
      { ingrediente: '1 cucharadita de comino' },
      { ingrediente: '100 ml de vino blanco o fino' },
      { ingrediente: '1 hoja de laurel' },
      { ingrediente: 'AOVE, pimienta negra, sal' },
    ],
    preparacion_es: [
      { paso: 'Sofríe la cebolla, el ajo y el pimiento en AOVE 10 minutos.' },
      { paso: 'Añade el tomate, el pimentón y el comino. Cocina 5 minutos.' },
      { paso: 'Incorpora las lentejas, la patata y la zanahoria. Cubre con agua y el vino.' },
      { paso: 'Cocina a fuego medio 35-40 minutos. Rectifica de sal.' },
    ],
    nota_food_mood_es: 'Tradición + Función. Las lentejas pardinas tienen más hierro y zinc que las castellanas. La combinación con patata y zanahoria genera glucosa cerebral estable. El pimentón ahumado aporta capsaicinoides que estimulan las endorfinas. Cimiento emocional.',
    variantes_es: [],
    tags: ['calma', 'cimiento', 'triptófano', 'española', 'legumbres', 'reconfort', 'dieta mediterránea'],
  },
  {
    id: 'esp-potaje-garbanzos-espinacas',
    nombre_es: '🇪🇸 Potaje de garbanzos y espinacas',
    mood_es: 'Confort & Reconfort',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'media', tiempo_preparacion_min: 60,
    temporada: 'invierno',
    contexto_es: 'Frío, tristeza invernal, necesito un abrazo en forma de plato',
    ingredientes_es: [
      { ingrediente: '500 g de garbanzos de calidad' },
      { ingrediente: '1 manojo de espinacas' },
      { ingrediente: '6 dientes de ajo' },
      { ingrediente: '1 cebolla' },
      { ingrediente: '400 g de tomate triturado' },
      { ingrediente: '2 hojas de laurel' },
      { ingrediente: '1 cucharadita de pimentón dulce' },
      { ingrediente: '200 ml de vino blanco' },
      { ingrediente: '2 huevos duros (para servir)' },
      { ingrediente: 'AOVE, sal, agua' },
    ],
    preparacion_es: [
      { paso: 'Remoja los garbanzos la noche anterior. Cuece 40-50 min con laurel.' },
      { paso: 'Haz un sofrito con cebolla, ajo, tomate y pimentón.' },
      { paso: 'Añade el sofrito a los garbanzos con el vino. Cocina 15 minutos.' },
      { paso: 'Incorpora las espinacas los últimos 5 minutos.' },
      { paso: 'Sirve con el huevo duro troceado por encima.' },
    ],
    nota_food_mood_es: 'Tradición + Función. El potaje de cuaresma es el plato de reconfort más completo: proteína vegetal + hierro + folatos + magnesio. Los garbanzos contienen inositol que reduce la ansiedad. Un abrazo que se come.',
    variantes_es: [],
    tags: ['confort', 'hierro', 'magnesio', 'española', 'invierno', 'garbanzos', 'tradición', 'dieta mediterránea'],
  },
  {
    id: 'esp-garbanzos-espinacas-limon-aceitunas',
    nombre_es: '🇪🇸 Garbanzos salteados con espinacas, limón y aceitunas',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'fácil', tiempo_preparacion_min: 10,
    temporada: '',
    contexto_es: 'Sin tiempo, pero sin querer descuidarme',
    ingredientes_es: [
      { ingrediente: '500 g de garbanzos cocidos (bote)' },
      { ingrediente: '200 g de espinacas frescas' },
      { ingrediente: '1 limón (zumo y ralladura)' },
      { ingrediente: '80 g de aceitunas kalamata deshuesadas' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '2 cucharadas de AOVE' },
      { ingrediente: 'sal y pimienta' },
      { ingrediente: 'queso feta o huevo (opcional)' },
    ],
    preparacion_es: [
      { paso: 'Calienta el AOVE con el ajo laminado a fuego medio.' },
      { paso: 'Añade los garbanzos escurridos y saltea 3-4 minutos.' },
      { paso: 'Incorpora las espinacas hasta que se ablanden.' },
      { paso: 'Añade las aceitunas, el zumo y la ralladura de limón.' },
    ],
    nota_food_mood_es: 'Tradición + Función. 10 minutos para proteína completa, hierro, magnesio, polifenoles del aceite y grasas de las aceitunas. El limón potencia la absorción del hierro vegetal. Las aceitunas kalamata tienen oleuropeína, el más potente neuroprotector del olivo.',
    variantes_es: [],
    tags: ['activación', 'express', '10 minutos', 'española', 'garbanzos', 'energía vegetal', 'dieta mediterránea'],
  },
  {
    id: 'esp-ensalada-naranja-sanguina-aceitunas',
    nombre_es: '🇪🇸 Ensalada de naranja sanguina con refrito de aceitunas negras',
    mood_es: 'Dieta Mediterránea Funcional',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'ensalada', dificultad: 'fácil', tiempo_preparacion_min: 15,
    temporada: 'invierno',
    contexto_es: 'Días grises, necesito color y energía',
    ingredientes_es: [
      { ingrediente: '2 naranjas sanguinas' },
      { ingrediente: '100 g de aceitunas negras' },
      { ingrediente: '½ cebolleta pequeña' },
      { ingrediente: '1 limón' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '2 ramas de tomillo' },
      { ingrediente: '1 cayena' },
      { ingrediente: '50 g de pipas de calabaza peladas' },
      { ingrediente: 'AOVE, sal, pimienta' },
    ],
    preparacion_es: [
      { paso: 'Pela las naranjas sanguinas a vivo y corta en rodajas.' },
      { paso: 'Haz un refrito con AOVE, ajo laminado, tomillo y cayena hasta dorar.' },
      { paso: 'Añade las aceitunas al refrito 1 minuto.' },
      { paso: 'Vierte el refrito caliente sobre las naranjas.' },
      { paso: 'Termina con pipas de calabaza, cebolleta y zumo de limón.' },
    ],
    nota_food_mood_es: 'Dieta Mediterránea Funcional. Las naranjas sanguinas contienen antocianinas (que las naranjas normales no tienen), con el mismo perfil neuroprotector que los arándanos. El refrito de AOVE caliente activa los polifenoles de las aceitunas. Una ensalada que ilumina el invierno.',
    variantes_es: [],
    tags: ['dieta mediterránea funcional', 'antocianinas', 'vitamina C', 'española', 'invierno', 'ensalada', 'neuroprotector'],
  },
  {
    id: 'esp-ensalada-hinojo-naranja-aceitunas',
    nombre_es: '🇪🇸 Ensalada de hinojo, naranja y aceitunas negras',
    mood_es: 'Reset & Microbiota',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'ensalada', dificultad: 'fácil', tiempo_preparacion_min: 15,
    temporada: 'invierno,primavera',
    contexto_es: 'Hinchazón, digestión pesada, necesito ligereza',
    ingredientes_es: [
      { ingrediente: '2 naranjas bien jugosas' },
      { ingrediente: '1 bulbo de hinojo grande' },
      { ingrediente: 'un puñado de aceitunas negras (kalamata o de Aragón)' },
      { ingrediente: 'cebolla roja o dulce al gusto' },
      { ingrediente: 'AOVE' },
      { ingrediente: 'chorrito de zumo de limón o vinagre' },
      { ingrediente: 'sal, pimienta' },
    ],
    preparacion_es: [
      { paso: 'Corta el hinojo en láminas muy finas.' },
      { paso: 'Pela las naranjas a vivo y trocea en gajos.' },
      { paso: 'Monta con las aceitunas y la cebolla en juliana fina.' },
      { paso: 'Aliña con AOVE, limón o vinagre, sal y pimienta.' },
    ],
    nota_food_mood_es: 'Tradición + Función. El hinojo contiene anetol con efecto carminativo (antihinchazón) y espasmolítico. La vitamina C de la naranja potencia la absorción del hierro de las aceitunas. Digestión activa que se hace sola.',
    variantes_es: [],
    tags: ['reset', 'digestión', 'hinojo', 'española', 'antihinchazón', 'ensalada', 'dieta mediterránea'],
  },
  {
    id: 'esp-pio-antequerano',
    nombre_es: '🇪🇸 Pío antequerano (ensalada andaluza de naranja y bacalao)',
    mood_es: 'Confort & Reconfort',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '25-65',
    premium_level: 1,
    tipo_plato: 'ensalada', dificultad: 'fácil', tiempo_preparacion_min: 20,
    temporada: 'invierno',
    contexto_es: 'Nostalgia, necesito raíces y sabor auténtico',
    ingredientes_es: [
      { ingrediente: '500 g de bacalao desalado' },
      { ingrediente: '3 naranjas grandes' },
      { ingrediente: '½ cebolla roja o cebolleta' },
      { ingrediente: '150 g de aceitunas negras' },
      { ingrediente: '2 huevos' },
      { ingrediente: '1 cucharada de vinagre de Jerez' },
      { ingrediente: 'cebollino picado (opcional)' },
      { ingrediente: 'AOVE, vinagre, sal' },
    ],
    preparacion_es: [
      { paso: 'Cuece los huevos 10 minutos. Enfría y pela.' },
      { paso: 'Desmiga el bacalao en lascas.' },
      { paso: 'Pela las naranjas a vivo y corta en rodajas.' },
      { paso: 'Monta: naranjas, bacalao, aceitunas, cebolla y huevo troceado.' },
      { paso: 'Aliña con AOVE, vinagre de Jerez y sal.' },
    ],
    nota_food_mood_es: 'Tradición + Función. El bacalao en salazón tiene más concentración de proteína que el fresco. La naranja y las aceitunas negras crean vitamina C + oleuropeína que protege el sistema nervioso. Historia en el plato.',
    variantes_es: [],
    tags: ['confort', 'omega-3', 'española', 'andalucía', 'antequera', 'bacalao', 'tradición', 'dieta mediterránea'],
  },
  {
    id: 'esp-sopa-castellana-ajo',
    nombre_es: '🇪🇸 Sopa castellana (sopa de ajo)',
    mood_es: 'Confort & Reconfort',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'sopa', dificultad: 'fácil', tiempo_preparacion_min: 20,
    temporada: 'otoño,invierno',
    contexto_es: 'Resfriado emocional, defensas bajas, necesito calor profundo',
    ingredientes_es: [
      { ingrediente: '3 dientes de ajo picado' },
      { ingrediente: '100 g de pan del día en rebanadas finas' },
      { ingrediente: '2 huevos' },
      { ingrediente: '1 cucharadita de pimentón' },
      { ingrediente: '100 ml de AOVE' },
      { ingrediente: '1 litro de agua caliente' },
      { ingrediente: 'sal' },
    ],
    preparacion_es: [
      { paso: 'Fríe el ajo en AOVE a fuego medio hasta dorar ligeramente.' },
      { paso: 'Añade el pan en rebanadas y dora por ambos lados.' },
      { paso: 'Incorpora el pimentón fuera del fuego. Remueve.' },
      { paso: 'Añade el agua caliente y hierve 5-10 minutos.' },
      { paso: 'Casca los huevos dentro, tapa y cuaja en el caldo.' },
    ],
    nota_food_mood_es: 'Tradición + Función. La allicina del ajo se activa al cortarlo y tiene efecto inmunomodulador documentado. El huevo escalfado en caldo conserva toda la colina y la vitamina D. El pan tostado tiene almidón resistente (prebiótico). Cuatro ingredientes, infinita profundidad.',
    variantes_es: [],
    tags: ['confort', 'inmunomodulador', 'española', 'castilla', 'allicina', 'sopa', 'tradición', 'dieta mediterránea'],
  },
  {
    id: 'esp-lentejas-verduras-completas',
    nombre_es: '🇪🇸 Lentejas con verduras completas',
    mood_es: 'Calma & Serenidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 1,
    tipo_plato: 'plato principal', dificultad: 'fácil', tiempo_preparacion_min: 50,
    temporada: 'otoño,invierno',
    contexto_es: 'Necesito un plato que funcione para todo y para todos',
    ingredientes_es: [
      { ingrediente: '400 g de lentejas pardinas o castellanas' },
      { ingrediente: '1,6 l de agua' },
      { ingrediente: '1 cebolla' },
      { ingrediente: '⅓ rama de apio' },
      { ingrediente: '1 zanahoria' },
      { ingrediente: '¼ pimiento verde' },
      { ingrediente: 'ajo, laurel, AOVE, sal' },
    ],
    preparacion_es: [
      { paso: 'Sofríe la cebolla, el ajo, el apio y el pimiento en AOVE 10 minutos.' },
      { paso: 'Añade las lentejas, la zanahoria y el laurel.' },
      { paso: 'Cubre con agua y cocina a fuego medio 35-40 minutos.' },
      { paso: 'Rectifica de sal. Añade un chorro de AOVE al servir.' },
    ],
    nota_food_mood_es: 'Tradición + Función. La fibra soluble de las lentejas alimenta directamente las bacterias productoras de GABA (neurotransmisor del equilibrio). El apio contiene apigenina con efecto ansiolítico. Un plato para todos los días y todos los estados de ánimo.',
    variantes_es: [],
    tags: ['calma', 'equilibrio', 'española', 'lentejas', 'GABA', 'universal', 'dieta mediterránea'],
  },
]

// ─────────────────────────────────────────────────────────────────────────────
const ALL_RECIPES = [...INTERNACIONALES, ...ESPANOLAS]

async function main() {
  console.log(`\n🌱 Seeding ${ALL_RECIPES.length} recetas funcionales (${INTERNACIONALES.length} internacionales + ${ESPANOLAS.length} españolas)...\n`)
  let ok = 0
  let err = 0

  for (const recipe of ALL_RECIPES) {
    const { error } = await supabase
      .from('recetas')
      .upsert(recipe, { onConflict: 'id' })

    if (error) {
      console.error(`❌ ${recipe.id}: ${error.message}`)
      err++
    } else {
      console.log(`✅ ${recipe.id}`)
      ok++
    }
  }

  console.log(`\n✅ Done: ${ok} ok, ${err} errors\n`)
}

main().catch(console.error)
