/**
 * seed-mediterraneas.ts
 * Añade recetas mediterráneas gratuitas para cada uno de los 6 estados emocionales.
 * Usa upsert → seguro de ejecutar varias veces sin borrar el catálogo existente.
 *
 * npx ts-node --project tsconfig.scripts.json scripts/seed-mediterraneas.ts
 */
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.RECETAS_SUPABASE_URL!,
  process.env.RECETAS_SUPABASE_KEY!
)

interface Receta {
  id: string
  nombre_es: string
  mood_es: string
  segmento: string
  sexo: string
  grupo_edad: string
  premium_level: number
  tipo_plato: string
  dificultad: string
  tiempo_preparacion_min: number
  temporada: string
  contexto_es: string
  ingredientes_es: { ingrediente: string }[]
  preparacion_es: { paso: string }[]
  nota_food_mood_es: string
  variantes_es: { variante: string }[]
  tags: string[]
}

const RECETAS: Receta[] = [

  // ─── ACTIVACIÓN & ENERGÍA ──────────────────────────────────────────────────
  {
    id: 'med-act-01',
    nombre_es: 'Tosta de Pan con Tomate, Anchoas y Aceite de Oliva',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'desayuno', dificultad: 'fácil',
    tiempo_preparacion_min: 8, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: 'pan de masa madre 2 rebanadas gruesas' },
      { ingrediente: '2 tomates maduros rallados' },
      { ingrediente: '6 anchoas en aceite de oliva' },
      { ingrediente: 'aceite de oliva virgen extra 2 cucharadas' },
      { ingrediente: 'ajo 1 diente' },
      { ingrediente: 'orégano seco' },
      { ingrediente: 'sal marina en escamas' },
    ],
    preparacion_es: [
      { paso: 'Tostar el pan hasta que esté crujiente por fuera y blando por dentro.' },
      { paso: 'Frotar el ajo crudo sobre la superficie caliente del pan.' },
      { paso: 'Extender el tomate rallado con presión; dejar que empape ligeramente.' },
      { paso: 'Colocar las anchoas encima y regar con aceite de oliva en hilo.' },
      { paso: 'Terminar con orégano y sal en escamas.' },
    ],
    nota_food_mood_es: 'Omega-3 de anchoas activa el nervio vago; polifenoles del tomate y el AOVE estimulan la síntesis de dopamina; la masa madre aporta ácido láctico que mejora la absorción de hierro.',
    variantes_es: [{ variante: 'Versión vegana: sustituir anchoas por aceitunas negras picadas y alcaparras.' }],
    tags: ['activación', 'mediterráneo', 'desayuno', 'masa madre', 'anchoas'],
  },
  {
    id: 'med-act-02',
    nombre_es: 'Gazpacho Energético con Pimiento Rojo y Jengibre',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 15, temporada: 'verano', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '600 g tomates maduros troceados' },
      { ingrediente: '1 pimiento rojo grande' },
      { ingrediente: '½ pepino pelado' },
      { ingrediente: '1 diente de ajo' },
      { ingrediente: '2 cm jengibre fresco rallado' },
      { ingrediente: '3 cucharadas aceite de oliva virgen extra' },
      { ingrediente: '1 cucharada vinagre de manzana sin filtrar' },
      { ingrediente: 'sal marina' },
    ],
    preparacion_es: [
      { paso: 'Batir todos los ingredientes hasta obtener una crema fina.' },
      { paso: 'Colar con un colador fino para eliminar pieles.' },
      { paso: 'Refrigerar 30 minutos como mínimo.' },
      { paso: 'Servir frío con un chorrito de AOVE y, si se quiere, pimiento picado por encima.' },
    ],
    nota_food_mood_es: 'El licopeno del tomate mejora la síntesis de óxido nítrico; el jengibre estimula los receptores de calor (TRPV1) elevando la termogénesis y la alerta; el vinagre de manzana frena el pico glucémico.',
    variantes_es: [{ variante: 'Añadir una cucharadita de cúrcuma para efecto antiinflamatorio adicional.' }],
    tags: ['activación', 'mediterráneo', 'verano', 'crudo', 'energía'],
  },
  {
    id: 'med-act-03',
    nombre_es: 'Pollo al Limón con Orégano, Ajo y Aceitunas Verdes',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 25, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '2 muslos de pollo sin piel' },
      { ingrediente: '1 limón (zumo y ralladura)' },
      { ingrediente: '3 dientes de ajo laminados' },
      { ingrediente: '1 cucharadita orégano seco' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: '80 g aceitunas verdes con hueso' },
      { ingrediente: 'sal marina y pimienta negra' },
    ],
    preparacion_es: [
      { paso: 'Marinar el pollo con zumo y ralladura de limón, ajo, orégano y AOVE durante 10 minutos.' },
      { paso: 'Calentar una sartén de hierro y dorar el pollo a fuego medio-alto 6 minutos por lado.' },
      { paso: 'Añadir las aceitunas y 3 cucharadas del agua de la marinada; tapar y cocinar 5 minutos más.' },
      { paso: 'Servir con el jugo de la sartén por encima.' },
    ],
    nota_food_mood_es: 'La tirosina del pollo es precursor directo de dopamina y norepinefrina; el limoneno de la ralladura activa receptores olfativos que estimulan la alerta; las aceitunas aportan oleocantal con efecto antiinflamatorio agudo.',
    variantes_es: [{ variante: 'Sustituir el pollo por contramuslos de pavo para mayor densidad de triptófano.' }],
    tags: ['activación', 'mediterráneo', 'pollo', 'limón', 'proteína'],
  },
  {
    id: 'med-act-04',
    nombre_es: 'Revuelto de Espinacas, Tomate Cherry y Huevo con Harissa',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'desayuno', dificultad: 'fácil',
    tiempo_preparacion_min: 10, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '3 huevos camperos' },
      { ingrediente: '80 g espinacas baby' },
      { ingrediente: '100 g tomates cherry' },
      { ingrediente: '1 cucharadita harissa (pasta de pimiento picante)' },
      { ingrediente: '1 cucharada aceite de oliva virgen extra' },
      { ingrediente: 'sal marina y comino molido' },
    ],
    preparacion_es: [
      { paso: 'Saltear los tomates cherry enteros en AOVE a fuego alto 2 minutos hasta que se abran.' },
      { paso: 'Añadir las espinacas y remover hasta que se marchiten.' },
      { paso: 'Bajar el fuego, agregar los huevos batidos con la harissa.' },
      { paso: 'Remover despacio hasta que el huevo cuaje cremoso.' },
      { paso: 'Terminar con comino y sal.' },
    ],
    nota_food_mood_es: 'La capsaicina de la harissa eleva la norepinefrina en 15 minutos; la colina del huevo es sustrato esencial para la acetilcolina (foco y memoria); el folato de las espinacas apoya la síntesis de serotonina.',
    variantes_es: [{ variante: 'Sin harissa: añadir pimentón ahumado y unas gotas de tabasco.' }],
    tags: ['activación', 'mediterráneo', 'huevo', 'espinacas', 'desayuno'],
  },
  {
    id: 'med-act-05',
    nombre_es: 'Ensalada Niçoise Funcional',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '1 lata de atún al natural (120 g)' },
      { ingrediente: '2 huevos duros' },
      { ingrediente: '150 g judías verdes blanqueadas' },
      { ingrediente: '1 tomate maduro en gajos' },
      { ingrediente: '6 aceitunas negras' },
      { ingrediente: '1 cucharada alcaparras' },
      { ingrediente: 'lechuga romana' },
      { ingrediente: 'vinagreta: AOVE + vinagre de manzana + mostaza Dijon + sal' },
    ],
    preparacion_es: [
      { paso: 'Blanquear las judías verdes 3 minutos en agua hirviendo con sal; enfriar en agua con hielo.' },
      { paso: 'Cocer los huevos 9 minutos; pelar y cortar en cuartos.' },
      { paso: 'Disponer todos los ingredientes sobre la lechuga sin mezclar.' },
      { paso: 'Emulsionar la vinagreta y aliñar justo antes de servir.' },
    ],
    nota_food_mood_es: 'Plato completo de proteína de alto valor biológico (atún + huevo), hierro no hemo con vitamina C (judías), y omega-3 EPA/DHA para activar el sistema dopaminérgico.',
    variantes_es: [{ variante: 'Añadir filetes de anchoa para doblar el aporte de omega-3.' }],
    tags: ['activación', 'mediterráneo', 'ensalada', 'atún', 'almuerzo'],
  },

  // ─── CALMA & EQUILIBRIO ────────────────────────────────────────────────────
  {
    id: 'med-cal-01',
    nombre_es: 'Sopa de Lentejas Rojas con Cúrcuma y Limón',
    mood_es: 'Calma & Equilibrio',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 25, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '200 g lentejas rojas' },
      { ingrediente: '1 cebolla mediana picada' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '1 cucharadita cúrcuma en polvo' },
      { ingrediente: '1 cucharadita comino molido' },
      { ingrediente: 'zumo de 1 limón' },
      { ingrediente: '800 ml caldo de verduras' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'cilantro fresco al gusto' },
    ],
    preparacion_es: [
      { paso: 'Sofreír cebolla y ajo en AOVE a fuego medio hasta que estén dorados.' },
      { paso: 'Añadir cúrcuma y comino; tostar 1 minuto removiendo.' },
      { paso: 'Incorporar las lentejas y el caldo; cocer 20 minutos.' },
      { paso: 'Triturar parcialmente dejando algo de textura.' },
      { paso: 'Añadir el zumo de limón y ajustar sal; servir con cilantro fresco.' },
    ],
    nota_food_mood_es: 'Las lentejas rojas son ricas en triptófano y magnesio, cofactores de la síntesis de serotonina; la curcumina modula la neuroinflamación; el calor de la sopa activa el nervio vago y reduce la respuesta al estrés.',
    variantes_es: [{ variante: 'Añadir una cucharada de miso al final (fuera del fuego) para probióticos adicionales.' }],
    tags: ['calma', 'mediterráneo', 'lentejas', 'sopa', 'cena'],
  },
  {
    id: 'med-cal-02',
    nombre_es: 'Crema de Calabacín con Menta y Yogur Griego',
    mood_es: 'Calma & Equilibrio',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: 'verano', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '3 calabacines medianos' },
      { ingrediente: '1 cebolla tierna' },
      { ingrediente: '600 ml caldo de verduras ligero' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: '3 cucharadas yogur griego entero' },
      { ingrediente: 'menta fresca un manojo' },
      { ingrediente: 'sal y pimienta blanca' },
    ],
    preparacion_es: [
      { paso: 'Sofreír la cebolla en AOVE hasta que sea transparente.' },
      { paso: 'Añadir el calabacín en rodajas; rehоgar 3 minutos.' },
      { paso: 'Cubrir con el caldo y cocer 12 minutos.' },
      { paso: 'Triturar con la menta fresca hasta obtener crema suave.' },
      { paso: 'Servir templada con una cucharada de yogur griego y unas hojas de menta.' },
    ],
    nota_food_mood_es: 'El magnesio del calabacín relaja la musculatura; el yogur griego aporta probióticos Lactobacillus que modulan el eje intestino-cerebro; la menta contiene linalol con efecto ansiolítico documentado.',
    variantes_es: [{ variante: 'Añadir 50 g de guisantes congelados para aumentar el aporte de triptófano.' }],
    tags: ['calma', 'mediterráneo', 'crema', 'calabacín', 'yogur'],
  },
  {
    id: 'med-cal-03',
    nombre_es: 'Bacalao al Vapor con Ajo Confitado y Aceite de Oliva',
    mood_es: 'Calma & Equilibrio',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '300 g lomo de bacalao desalado' },
      { ingrediente: '6 dientes de ajo' },
      { ingrediente: '4 cucharadas aceite de oliva virgen extra' },
      { ingrediente: '1 limón (zumo)' },
      { ingrediente: 'perejil fresco' },
      { ingrediente: 'pimentón dulce ahumado' },
    ],
    preparacion_es: [
      { paso: 'Confitar el ajo: cubrir los dientes con AOVE y calentar a fuego muy bajo 15 minutos; no debe freír.' },
      { paso: 'Cocer el bacalao al vapor 8 minutos.' },
      { paso: 'Disponer el bacalao en plato, colocar los ajos confitados encima.' },
      { paso: 'Emulsionar el aceite del confitado con el zumo de limón y verter en hilo.' },
      { paso: 'Terminar con perejil picado y pimentón ahumado.' },
    ],
    nota_food_mood_es: 'El bacalao es una de las fuentes más puras de proteína con mínimo cortisol alimentario; el ajo confitado (no crudo) libera alicina transformada que regula el sistema nervioso autónomo sin irritar la mucosa; la cocción al vapor preserva el magnesio.',
    variantes_es: [{ variante: 'Sustituir el bacalao por lubina o dorada al vapor.' }],
    tags: ['calma', 'mediterráneo', 'bacalao', 'vapor', 'cena'],
  },
  {
    id: 'med-cal-04',
    nombre_es: 'Bol de Quinoa con Pepino, Feta y Hierbas Frescas',
    mood_es: 'Calma & Equilibrio',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 15, temporada: 'verano', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '180 g quinoa cocida (fría)' },
      { ingrediente: '½ pepino en cubos' },
      { ingrediente: '80 g queso feta desmenuzado' },
      { ingrediente: '20 aceitunas kalamata' },
      { ingrediente: 'menta y eneldo frescos picados' },
      { ingrediente: 'zumo de 1 limón' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'sal marina y pimienta negra' },
    ],
    preparacion_es: [
      { paso: 'Mezclar la quinoa fría con el pepino, las aceitunas y el feta.' },
      { paso: 'Añadir las hierbas frescas y mezclar con suavidad.' },
      { paso: 'Aliñar con zumo de limón y AOVE.' },
      { paso: 'Servir a temperatura ambiente o ligeramente fría.' },
    ],
    nota_food_mood_es: 'La quinoa es el único cereal con perfil completo de aminoácidos incluyendo triptófano; el feta fermento aporta bacterias ácido-lácticas; las aceitunas kalamata concentran polifenoles que regulan el cortisol.',
    variantes_es: [{ variante: 'Versión vegana: sustituir feta por tofu ahumado desmenuzado.' }],
    tags: ['calma', 'mediterráneo', 'quinoa', 'feta', 'almuerzo'],
  },
  {
    id: 'med-cal-05',
    nombre_es: 'Tortilla de Patata con Aceite de Oliva Virgen Extra y Cebolla Caramelizada',
    mood_es: 'Calma & Equilibrio',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'media',
    tiempo_preparacion_min: 30, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '3 patatas medianas peladas y laminadas finas' },
      { ingrediente: '1 cebolla grande laminada' },
      { ingrediente: '4 huevos camperos' },
      { ingrediente: '80 ml aceite de oliva virgen extra' },
      { ingrediente: 'sal marina' },
    ],
    preparacion_es: [
      { paso: 'Caramelizar la cebolla en AOVE a fuego muy bajo 20 minutos, removiendo ocasionalmente.' },
      { paso: 'Añadir las patatas laminadas y confitar junto con la cebolla 15 minutos más.' },
      { paso: 'Escurrir el exceso de aceite; mezclar con los huevos batidos y sal.' },
      { paso: 'Cuajar en sartén antiadherente a fuego medio, 4 minutos por lado.' },
      { paso: 'Dejar reposar 5 minutos antes de cortar.' },
    ],
    nota_food_mood_es: 'La cocción lenta de la cebolla genera fructooligosacáridos prebióticos; el almidón resistente de la patata enfriada alimenta Akkermansia muciniphila; la colina del huevo apoya la síntesis de acetilcolina para el descanso nocturno.',
    variantes_es: [{ variante: 'Añadir espinacas baby al mezclar con el huevo para aumentar el folato.' }],
    tags: ['calma', 'mediterráneo', 'tortilla', 'patata', 'huevo'],
  },

  // ─── FOCUS & CLARIDAD MENTAL ──────────────────────────────────────────────
  {
    id: 'med-foc-01',
    nombre_es: 'Ensalada de Rúcula, Nueces, Parmesano y Vinagre Balsámico',
    mood_es: 'Focus & Claridad Mental',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 8, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '100 g rúcula fresca' },
      { ingrediente: '40 g nueces peladas' },
      { ingrediente: '30 g parmesano reggiano en lascas' },
      { ingrediente: '1 cucharada vinagre balsámico de Módena' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'sal y pimienta negra' },
    ],
    preparacion_es: [
      { paso: 'Tostar las nueces en seco 2 minutos en sartén; dejar enfriar.' },
      { paso: 'Disponer la rúcula en el plato.' },
      { paso: 'Añadir las nueces tostadas y las lascas de parmesano.' },
      { paso: 'Emulsionar el balsámico con el AOVE; aliñar al momento de servir.' },
    ],
    nota_food_mood_es: 'Las nueces son la nuez con mayor concentración de ALA y polifenoles que estimulan el BDNF; el glucosinolato de la rúcula activa la vía Nrf2 neuroprotectora; el parmesano aporta tirosina y GABA naturales.',
    variantes_es: [{ variante: 'Añadir higos frescos en temporada para aumentar la densidad polifenólica.' }],
    tags: ['foco', 'mediterráneo', 'ensalada', 'nueces', 'rúcula'],
  },
  {
    id: 'med-foc-02',
    nombre_es: 'Sardinillas en Tosta con Tomate Rallado y Orégano',
    mood_es: 'Focus & Claridad Mental',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'desayuno', dificultad: 'fácil',
    tiempo_preparacion_min: 8, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '1 lata de sardinillas en aceite de oliva' },
      { ingrediente: '2 rebanadas pan de centeno' },
      { ingrediente: '1 tomate maduro rallado' },
      { ingrediente: '1 cucharadita orégano seco' },
      { ingrediente: 'aceite de oliva virgen extra' },
      { ingrediente: 'gotas de limón' },
    ],
    preparacion_es: [
      { paso: 'Tostar el pan de centeno.' },
      { paso: 'Extender el tomate rallado sobre cada tosta.' },
      { paso: 'Colocar las sardinillas escurridas encima.' },
      { paso: 'Terminar con orégano, un hilo de AOVE y unas gotas de limón.' },
    ],
    nota_food_mood_es: 'Las sardinillas concentran EPA y DHA, ácidos grasos que aumentan la fluidez de las membranas neuronales; el pan de centeno tiene índice glucémico bajo → glucosa estable = foco sostenido; el licopeno del tomate protege los lípidos cerebrales de la oxidación.',
    variantes_es: [{ variante: 'Añadir medio aguacate para doblar el aporte de grasas monoinsaturadas.' }],
    tags: ['foco', 'mediterráneo', 'sardinas', 'tosta', 'omega-3'],
  },
  {
    id: 'med-foc-03',
    nombre_es: 'Carpaccio de Remolacha con Naranja y Nueces Tostadas',
    mood_es: 'Focus & Claridad Mental',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 15, temporada: 'otoño-invierno', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '2 remolachas cocidas laminadas muy finas' },
      { ingrediente: '1 naranja en gajos pelados en vivo' },
      { ingrediente: '30 g nueces tostadas' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'vinagre de jerez' },
      { ingrediente: 'romero fresco' },
      { ingrediente: 'sal marina' },
    ],
    preparacion_es: [
      { paso: 'Disponer las láminas de remolacha en el plato superponiéndolas.' },
      { paso: 'Intercalar los gajos de naranja entre las láminas.' },
      { paso: 'Esparcir las nueces tostadas y las hojas de romero.' },
      { paso: 'Emulsionar AOVE y vinagre de jerez; aliñar y servir.' },
    ],
    nota_food_mood_es: 'Los nitratos de la remolacha generan óxido nítrico que mejora la perfusión cerebral en 90 minutos; la vitamina C de la naranja aumenta la biodisponibilidad del hierro y apoya la síntesis de norepinefrina; el romero contiene ácido rosmarínico que inhibe la degradación de acetilcolina.',
    variantes_es: [{ variante: 'Añadir queso de cabra desmenuzado para aumentar la densidad proteica.' }],
    tags: ['foco', 'mediterráneo', 'remolacha', 'naranja', 'nueces'],
  },
  {
    id: 'med-foc-04',
    nombre_es: 'Sopa de Espinacas con Huevo Pochado y Comino',
    mood_es: 'Focus & Claridad Mental',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 18, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '150 g espinacas frescas' },
      { ingrediente: '2 huevos camperos' },
      { ingrediente: '1 cebolla pequeña' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '700 ml caldo de verduras' },
      { ingrediente: '1 cucharadita comino molido' },
      { ingrediente: '1 cucharada vinagre blanco (para pochar)' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
    ],
    preparacion_es: [
      { paso: 'Sofreír cebolla y ajo en AOVE; añadir comino y tostar 1 minuto.' },
      { paso: 'Incorporar las espinacas y el caldo; cocer 8 minutos.' },
      { paso: 'Triturar suavemente la mitad de la sopa para dar cuerpo sin perder textura.' },
      { paso: 'Pochar los huevos: agua hirviendo con vinagre, 3 minutos.' },
      { paso: 'Servir la sopa con el huevo pochado encima.' },
    ],
    nota_food_mood_es: 'El folato de las espinacas es cofactor de la síntesis de todos los neurotransmisores; el huevo pochado preserva la colina intacta (se destruye con la sobrecocción); el comino activa enzimas digestivas que mejoran la absorción de nutrientes clave.',
    variantes_es: [{ variante: 'Añadir una cucharadita de tahini al servir para incorporar calcio y sésamo.' }],
    tags: ['foco', 'mediterráneo', 'espinacas', 'huevo', 'sopa'],
  },
  {
    id: 'med-foc-05',
    nombre_es: 'Anchoas sobre Tosta de Centeno con Mantequilla de Almendras y Semillas de Chía',
    mood_es: 'Focus & Claridad Mental',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'desayuno', dificultad: 'fácil',
    tiempo_preparacion_min: 6, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '2 tostas de pan de centeno' },
      { ingrediente: '6 anchoas en aceite de oliva' },
      { ingrediente: '2 cucharadas mantequilla de almendras' },
      { ingrediente: '1 cucharada semillas de chía' },
      { ingrediente: 'gotas de limón' },
      { ingrediente: 'pimentón dulce' },
    ],
    preparacion_es: [
      { paso: 'Tostar el centeno.' },
      { paso: 'Extender la mantequilla de almendras en cada tosta.' },
      { paso: 'Colocar 3 anchoas encima de cada tosta.' },
      { paso: 'Espolvorear las semillas de chía y el pimentón.' },
      { paso: 'Terminar con unas gotas de limón.' },
    ],
    nota_food_mood_es: 'Combinación diseñada para máxima densidad cognitiva: omega-3 EPA de anchoas + ALA de chía + vitamina E de almendras = sinergia antioxidante neuronal; el pan de centeno aporta beta-glucanos que sostienen la glucosa durante 4-5 horas.',
    variantes_es: [{ variante: 'Sustituir anchoas por sardinas si se prefiere sabor más suave.' }],
    tags: ['foco', 'mediterráneo', 'anchoas', 'almendras', 'chía'],
  },

  // ─── SOCIAL & PLACER COMPARTIDO ───────────────────────────────────────────
  {
    id: 'med-soc-01',
    nombre_es: 'Hummus Casero con Aceite de Oliva, Pimentón Ahumado y Za\'atar',
    mood_es: 'Social & Placer Compartido',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'snack', dificultad: 'fácil',
    tiempo_preparacion_min: 10, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '400 g garbanzos cocidos (o 1 lata)' },
      { ingrediente: '3 cucharadas tahini' },
      { ingrediente: 'zumo de 1 limón' },
      { ingrediente: '1 diente de ajo' },
      { ingrediente: '3 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'sal y comino' },
      { ingrediente: 'za\'atar y pimentón ahumado para servir' },
    ],
    preparacion_es: [
      { paso: 'Batir los garbanzos con el tahini, el limón, el ajo y el AOVE hasta crema muy lisa.' },
      { paso: 'Si la textura es demasiado espesa, añadir 2-3 cucharadas del líquido de la lata (aquafaba).' },
      { paso: 'Ajustar sal y comino.' },
      { paso: 'Servir en cuenco con un surco central donde verter AOVE, za\'atar y pimentón.' },
    ],
    nota_food_mood_es: 'Los garbanzos son la fuente vegetal más rica en triptófano; el tahini aporta metionina complementaria y el calcio que activa la conversión de triptófano a serotonina; compartir un cuenco común activa circuitos de oxitocina.',
    variantes_es: [{ variante: 'Versión remolacha: añadir 100 g de remolacha cocida al batir para color y nitratos.' }],
    tags: ['social', 'mediterráneo', 'hummus', 'garbanzos', 'compartir'],
  },
  {
    id: 'med-soc-02',
    nombre_es: 'Mejillones al Vapor con Vino Blanco, Ajo y Perejil',
    mood_es: 'Social & Placer Compartido',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 15, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '1 kg mejillones limpios' },
      { ingrediente: '150 ml vino blanco seco' },
      { ingrediente: '3 dientes de ajo laminados' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'perejil fresco abundante' },
      { ingrediente: '1 guindilla seca (opcional)' },
      { ingrediente: 'pan rústico para mojar' },
    ],
    preparacion_es: [
      { paso: 'Calentar el AOVE en cazuela grande con el ajo y la guindilla a fuego medio.' },
      { paso: 'Añadir el vino blanco y subir el fuego.' },
      { paso: 'Incorporar los mejillones; tapar y cocer 4-5 minutos agitando la cazuela.' },
      { paso: 'Desechar los que no se hayan abierto.' },
      { paso: 'Espolvorear perejil abundante y servir inmediatamente en la misma cazuela.' },
    ],
    nota_food_mood_es: 'Los mejillones concentran zinc, vitamina B12 y omega-3 de cadena larga; el ritual de cocinar y mojar pan en la salsa activa circuitos de recompensa compartida; el zinc apoya la síntesis de oxitocina.',
    variantes_es: [{ variante: 'Añadir 200 g de tomate cherry al sofrito para un caldo más mediterráneo.' }],
    tags: ['social', 'mediterráneo', 'mejillones', 'mariscos', 'compartir'],
  },
  {
    id: 'med-soc-03',
    nombre_es: 'Tabla de Antipasto Mediterráneo',
    mood_es: 'Social & Placer Compartido',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'snack', dificultad: 'fácil',
    tiempo_preparacion_min: 10, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '100 g queso feta en cubos' },
      { ingrediente: '80 g aceitunas kalamata y verdes mezcladas' },
      { ingrediente: '150 g tomates cherry de colores' },
      { ingrediente: '60 g pimientos asados en tiras' },
      { ingrediente: '1 pepino en bastones' },
      { ingrediente: 'alcaparras y pepinillos' },
      { ingrediente: 'pan de pita o regañadas' },
      { ingrediente: 'aceite de oliva virgen extra y za\'atar' },
    ],
    preparacion_es: [
      { paso: 'Disponer cada ingrediente en grupos separados en una tabla grande de madera o mármol.' },
      { paso: 'Colocar un cuenco pequeño con AOVE mezclado con za\'atar al centro.' },
      { paso: 'Servir con el pan al lado.' },
    ],
    nota_food_mood_es: 'Comer con las manos activa circuitos sensoriales de contacto que refuerzan la presencia social; la variedad de colores indica diversidad polifenólica que alimenta distintas cepas del microbioma; las aceitunas fermentadas aportan compuestos que modulan el eje HPA.',
    variantes_es: [{ variante: 'Añadir jamón ibérico o bresaola para más proteína completa.' }],
    tags: ['social', 'mediterráneo', 'tabla', 'antipasto', 'compartir'],
  },
  {
    id: 'med-soc-04',
    nombre_es: 'Pan de Pita con Tzatziki, Vegetales Asados y Hierbas',
    mood_es: 'Social & Placer Compartido',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '4 pitas de trigo integral' },
      { ingrediente: '200 g yogur griego entero' },
      { ingrediente: '1 pepino rallado y escurrido' },
      { ingrediente: '1 diente de ajo rallado' },
      { ingrediente: '2 cucharadas AOVE' },
      { ingrediente: 'eneldo fresco' },
      { ingrediente: '1 berenjena y 1 pimiento rojo asados y en tiras' },
      { ingrediente: 'menta fresca' },
    ],
    preparacion_es: [
      { paso: 'Mezclar el yogur con el pepino escurrido, el ajo, el eneldo y el AOVE para el tzatziki.' },
      { paso: 'Asar la berenjena y el pimiento al horno 20 minutos a 200°C o directamente en llama.' },
      { paso: 'Calentar las pitas.' },
      { paso: 'Montar: tzatziki en la base, vegetales asados encima, menta fresca al final.' },
    ],
    nota_food_mood_es: 'El yogur griego aporta probióticos Streptococcus thermophilus que modulan el humor vía eje intestino-cerebro; el formato compartido de montar juntos activa la cooperación, que libera oxitocina; la berenjena contiene antocianinas con efecto neuroprotector.',
    variantes_es: [{ variante: 'Añadir falafel casero para versión vegana con proteína completa.' }],
    tags: ['social', 'mediterráneo', 'pita', 'tzatziki', 'vegetales'],
  },
  {
    id: 'med-soc-05',
    nombre_es: 'Pasta al Pesto de Albahaca con Nueces y Parmesano',
    mood_es: 'Social & Placer Compartido',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: 'verano', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '320 g espagueti o linguini' },
      { ingrediente: '40 g albahaca fresca' },
      { ingrediente: '30 g nueces (en vez de piñones)' },
      { ingrediente: '30 g parmesano reggiano rallado' },
      { ingrediente: '1 diente de ajo' },
      { ingrediente: '5 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'sal y pimienta negra' },
    ],
    preparacion_es: [
      { paso: 'Batir la albahaca, las nueces, el ajo y el parmesano en mortero o batidora.' },
      { paso: 'Incorporar el AOVE en hilo hasta obtener crema.' },
      { paso: 'Cocer la pasta al dente; reservar un cazo del agua de cocción.' },
      { paso: 'Mezclar la pasta escurrida con el pesto añadiendo agua de cocción para ligar.' },
      { paso: 'Servir inmediatamente con más parmesano.' },
    ],
    nota_food_mood_es: 'El ácido láctico del parmesano de larga maduración actúa como postbiótico; las nueces aportan omega-3 ALA y serotonina precursores; el aroma de la albahaca fresca activa el sistema límbico, creando recuerdos positivos asociados al placer compartido.',
    variantes_es: [{ variante: 'Añadir tomates cherry asados para un pesto rosso y más licopeno.' }],
    tags: ['social', 'mediterráneo', 'pasta', 'pesto', 'nueces'],
  },

  // ─── RESET & LIGEREZA ─────────────────────────────────────────────────────
  {
    id: 'med-res-01',
    nombre_es: 'Caldo Depurativo de Verduras con Hinojo y Cúrcuma',
    mood_es: 'Reset & Ligereza',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 30, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '1 bulbo de hinojo con sus hojas verdes' },
      { ingrediente: '2 zanahorias' },
      { ingrediente: '1 rama de apio' },
      { ingrediente: '1 puerro (la parte verde)' },
      { ingrediente: '1 cucharadita cúrcuma en polvo' },
      { ingrediente: '1 cm jengibre fresco' },
      { ingrediente: 'zumo de ½ limón' },
      { ingrediente: '1,2 litros de agua filtrada' },
      { ingrediente: 'sal marina' },
    ],
    preparacion_es: [
      { paso: 'Trocear todas las verduras toscamente.' },
      { paso: 'Cocer a fuego suave con el agua, la cúrcuma y el jengibre durante 25 minutos.' },
      { paso: 'Colar y reservar el caldo; descartar o compostar los sólidos.' },
      { paso: 'Añadir el zumo de limón fuera del fuego.' },
      { paso: 'Servir caliente en taza.' },
    ],
    nota_food_mood_es: 'El anetol del hinojo tiene efecto antiespasmódico y estimula las enzimas hepáticas de fase I; la curcumina activa el factor de transcripción Nrf2 que coordina la respuesta antioxidante celular; el caldo caliente sin fibra da descanso digestivo mientras nutre.',
    variantes_es: [{ variante: 'Añadir una cucharada de miso después de colar para un extra de probióticos.' }],
    tags: ['reset', 'mediterráneo', 'caldo', 'hinojo', 'depurativo'],
  },
  {
    id: 'med-res-02',
    nombre_es: 'Alcachofas al Vapor con Vinagreta de Limón y Hierbas',
    mood_es: 'Reset & Ligereza',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 30, temporada: 'primavera', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '2 alcachofas grandes' },
      { ingrediente: 'zumo de 1 limón' },
      { ingrediente: '3 cucharadas aceite de oliva virgen extra' },
      { ingrediente: '1 cucharadita mostaza Dijon' },
      { ingrediente: 'perejil y estragón frescos picados' },
      { ingrediente: 'sal marina' },
    ],
    preparacion_es: [
      { paso: 'Cortar los tallos y las hojas externas más duras de las alcachofas.' },
      { paso: 'Cocer al vapor sobre agua con limón durante 25-30 minutos hasta que las hojas salgan con facilidad.' },
      { paso: 'Preparar la vinagreta emulsionando el AOVE con el limón, la mostaza y las hierbas.' },
      { paso: 'Servir las alcachofas enteras con la vinagreta en un cuenco para mojar.' },
    ],
    nota_food_mood_es: 'La cinarina y la silimarina de la alcachofa estimulan la secreción biliar y el flujo hepático; la inulina que contienen es un prebiótico que nutre selectivamente Bifidobacterium; comer hoja a hoja induce el mindful eating que activa el nervio vago.',
    variantes_es: [{ variante: 'Servir con alioli ligero (yogur griego + ajo + limón) en vez de vinagreta.' }],
    tags: ['reset', 'mediterráneo', 'alcachofas', 'hígado', 'depurativo'],
  },
  {
    id: 'med-res-03',
    nombre_es: 'Caballa al Horno con Hinojo, Limón y Alcaparras',
    mood_es: 'Reset & Ligereza',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 25, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '2 filetes de caballa frescos' },
      { ingrediente: '1 bulbo de hinojo laminado fino' },
      { ingrediente: '1 limón en rodajas' },
      { ingrediente: '2 cucharadas alcaparras' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'eneldo fresco' },
      { ingrediente: 'sal y pimienta negra' },
    ],
    preparacion_es: [
      { paso: 'Precalentar el horno a 190°C.' },
      { paso: 'Disponer el hinojo laminado en una bandeja; colocar la caballa encima.' },
      { paso: 'Cubrir con rodajas de limón, alcaparras y eneldo; regar con AOVE.' },
      { paso: 'Hornear 18-20 minutos.' },
    ],
    nota_food_mood_es: 'La caballa es uno de los pescados azules con mayor concentración de EPA y DHA por gramo; los omega-3 reducen la expresión de citoquinas proinflamatorias IL-6 y TNF-α; las alcaparras concentran rutina, un flavonoide que estabiliza los mastocitos intestinales.',
    variantes_es: [{ variante: 'Sustituir la caballa por sardinas frescas para el mismo perfil nutricional.' }],
    tags: ['reset', 'mediterráneo', 'caballa', 'hinojo', 'omega-3'],
  },
  {
    id: 'med-res-04',
    nombre_es: 'Sopa Fría de Pepino, Yogur y Eneldo',
    mood_es: 'Reset & Ligereza',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 10, temporada: 'verano', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '2 pepinos pelados' },
      { ingrediente: '200 g yogur griego entero' },
      { ingrediente: 'zumo de ½ limón' },
      { ingrediente: '1 diente de ajo pequeño' },
      { ingrediente: 'eneldo fresco abundante' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'sal marina y pimienta blanca' },
    ],
    preparacion_es: [
      { paso: 'Reservar ¼ de pepino en cubos para la guarnición.' },
      { paso: 'Batir el resto del pepino con el yogur, el limón, el ajo y el eneldo hasta crema.' },
      { paso: 'Ajustar la sal y refrigerar 20 minutos.' },
      { paso: 'Servir frío con los cubos de pepino, un hilo de AOVE y una ramita de eneldo.' },
    ],
    nota_food_mood_es: 'El pepino tiene un 96% de agua + electrolitos naturales que rehidatan las células sin esfuerzo digestivo; el yogur griego aporta probióticos y proteína con mínima carga de procesado; esta sopa es de las preparaciones con menor carga glucémica del recetario.',
    variantes_es: [{ variante: 'Añadir menta fresca en vez de eneldo para efecto más refrescante.' }],
    tags: ['reset', 'mediterráneo', 'pepino', 'yogur', 'sopa fría'],
  },
  {
    id: 'med-res-05',
    nombre_es: 'Ensalada de Endivias con Naranja, Nueces y Aceite de Oliva',
    mood_es: 'Reset & Ligereza',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 10, temporada: 'invierno', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '3 endivias separadas en hojas' },
      { ingrediente: '2 naranjas en gajos pelados en vivo' },
      { ingrediente: '30 g nueces tostadas' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'vinagre de manzana sin filtrar' },
      { ingrediente: 'sal marina' },
    ],
    preparacion_es: [
      { paso: 'Separar las hojas de endivia y disponerlas como barquitos en el plato.' },
      { paso: 'Colocar un gajo de naranja y una nuez en cada hoja.' },
      { paso: 'Aliñar con AOVE y vinagre de manzana.' },
      { paso: 'Terminar con sal marina en escamas.' },
    ],
    nota_food_mood_es: 'La inulina de la endivia alimenta Bifidobacterium y Faecalibacterium prausnitzii, bacterias antiinflamatorias clave; el amargor activa la secreción biliar; la naranja aporta vitamina C que potencia la absorción del hierro no hemo de toda la comida.',
    variantes_es: [{ variante: 'Añadir lonchas finas de jamón ibérico para incorporar proteína y umami.' }],
    tags: ['reset', 'mediterráneo', 'endivias', 'naranja', 'invierno'],
  },

  // ─── CONFORT & CALIDEZ ────────────────────────────────────────────────────
  {
    id: 'med-con-01',
    nombre_es: 'Sopa de Tomate Asado con Albahaca Fresca',
    mood_es: 'Confort & Calidez',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 35, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '800 g tomates pera o rama' },
      { ingrediente: '1 cebolla morada' },
      { ingrediente: '4 dientes de ajo' },
      { ingrediente: '3 cucharadas aceite de oliva virgen extra' },
      { ingrediente: '500 ml caldo de verduras' },
      { ingrediente: 'albahaca fresca abundante' },
      { ingrediente: 'sal marina y pimienta negra' },
      { ingrediente: 'pan rústico tostado para servir' },
    ],
    preparacion_es: [
      { paso: 'Cortar los tomates y la cebolla por la mitad; colocar con el ajo en bandeja.' },
      { paso: 'Regar con AOVE y asar al horno a 200°C durante 25 minutos hasta que caramelicen.' },
      { paso: 'Trasladar al cazo con el caldo y triturar.' },
      { paso: 'Colar para obtener crema sedosa.' },
      { paso: 'Servir caliente con albahaca fresca y una tosta de pan.' },
    ],
    nota_food_mood_es: 'El asado concentra el licopeno y lo vuelve 3 veces más biodisponible que el tomate crudo; el GABA natural del tomate maduro y el calor de la sopa estimulan el nervio vago; el aroma de la albahaca fresca activa el sistema límbico creando sensación de hogar.',
    variantes_es: [{ variante: 'Añadir 100 ml de leche de coco al triturar para textura más cremosa.' }],
    tags: ['confort', 'mediterráneo', 'tomate', 'sopa', 'cena'],
  },
  {
    id: 'med-con-02',
    nombre_es: 'Garbanzos Guisados con Espinacas y Huevo Pochado',
    mood_es: 'Confort & Calidez',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '400 g garbanzos cocidos (1 lata)' },
      { ingrediente: '150 g espinacas frescas' },
      { ingrediente: '2 huevos camperos' },
      { ingrediente: '1 cebolla' },
      { ingrediente: '3 dientes de ajo' },
      { ingrediente: '1 cucharadita pimentón dulce ahumado' },
      { ingrediente: '1 cucharadita comino' },
      { ingrediente: '200 ml tomate triturado' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
    ],
    preparacion_es: [
      { paso: 'Sofreír la cebolla y el ajo en AOVE; añadir pimentón y comino, tostar 1 minuto.' },
      { paso: 'Incorporar el tomate y cocer 5 minutos.' },
      { paso: 'Añadir los garbanzos y 100 ml de agua; cocer 8 minutos.' },
      { paso: 'Agregar las espinacas y remover hasta que se integren.' },
      { paso: 'Hacer dos huecos y pochar los huevos directamente en el guiso tapado 4 minutos.' },
    ],
    nota_food_mood_es: 'Guiso construido sobre el trío serotonina-triptófano-magnesio; los garbanzos aportan fibra que nutre Roseburia intestinalis, bacteria productora de butirato; la calidez del guiso activa el sistema nervioso parasimpático ("calor = seguridad").',
    variantes_es: [{ variante: 'Añadir una cucharada de tahini al servir para grasas saludables adicionales.' }],
    tags: ['confort', 'mediterráneo', 'garbanzos', 'espinacas', 'guiso'],
  },
  {
    id: 'med-con-03',
    nombre_es: 'Pasta Integral al Pomodoro con Albahaca y Parmesano',
    mood_es: 'Confort & Calidez',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 25, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '300 g pasta integral (spaghetti o penne)' },
      { ingrediente: '400 g tomates pelados enteros (lata)' },
      { ingrediente: '3 dientes de ajo' },
      { ingrediente: '3 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'albahaca fresca' },
      { ingrediente: '40 g parmesano reggiano rallado' },
      { ingrediente: 'sal marina y pimienta negra' },
    ],
    preparacion_es: [
      { paso: 'Dorar el ajo en láminas en el AOVE a fuego medio; retirar antes de que se queme.' },
      { paso: 'Añadir los tomates y aplastar con una cuchara de madera.' },
      { paso: 'Cocer la salsa a fuego suave 15 minutos hasta que reduzca.' },
      { paso: 'Cocer la pasta al dente; añadir a la salsa con un cazo del agua de cocción.' },
      { paso: 'Apagar el fuego, añadir albahaca fresca y el parmesano; servir.' },
    ],
    nota_food_mood_es: 'El almidón resistente de la pasta integral enfriada ligeramente alimenta Lactobacillus; el parmesano de larga curación contiene GABA activo y ácido láctico; el aroma del ajo en aceite caliente activa el núcleo accumbens, el centro del placer anticipatorio.',
    variantes_es: [{ variante: 'Añadir 8 aceitunas negras picadas a la salsa para polifenoles adicionales.' }],
    tags: ['confort', 'mediterráneo', 'pasta', 'tomate', 'cena'],
  },
  {
    id: 'med-con-04',
    nombre_es: 'Crema de Zanahoria con Jengibre, Naranja y Aceite de Sésamo',
    mood_es: 'Confort & Calidez',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 25, temporada: '', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '500 g zanahorias' },
      { ingrediente: '2 cm jengibre fresco' },
      { ingrediente: 'zumo y ralladura de 1 naranja' },
      { ingrediente: '1 cebolla' },
      { ingrediente: '700 ml caldo de verduras' },
      { ingrediente: '1 cucharadita aceite de sésamo tostado' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'sal marina' },
    ],
    preparacion_es: [
      { paso: 'Sofreír cebolla y jengibre en AOVE hasta que ablanden.' },
      { paso: 'Añadir las zanahorias troceadas y el caldo; cocer 20 minutos.' },
      { paso: 'Triturar hasta crema muy fina.' },
      { paso: 'Incorporar el zumo y la ralladura de naranja; ajustar sal.' },
      { paso: 'Servir con un hilo de aceite de sésamo tostado.' },
    ],
    nota_food_mood_es: 'Los beta-carotenos de la zanahoria son precursores de vitamina A, esencial para la integridad de la mucosa intestinal; los gingeroles del jengibre tienen efecto termogénico y antiemético; el aceite de sésamo aporta sesamol, polifenol con efecto antidepresivo en modelos animales.',
    variantes_es: [{ variante: 'Añadir 1 cucharada de mantequilla de cacahuete al servir para textura cremosa y proteína.' }],
    tags: ['confort', 'mediterráneo', 'zanahoria', 'jengibre', 'crema'],
  },
  {
    id: 'med-con-05',
    nombre_es: 'Lentejas Beluga con Chorizo de Pavo y Pimentón de la Vera',
    mood_es: 'Confort & Calidez',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: '18-65',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 30, temporada: 'otoño-invierno', contexto_es: '',
    ingredientes_es: [
      { ingrediente: '200 g lentejas beluga (negras)' },
      { ingrediente: '100 g chorizo de pavo en rodajas' },
      { ingrediente: '1 cebolla' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '1 cucharadita pimentón de la Vera ahumado' },
      { ingrediente: '1 hoja de laurel' },
      { ingrediente: '2 cucharadas aceite de oliva virgen extra' },
      { ingrediente: 'sal marina' },
    ],
    preparacion_es: [
      { paso: 'Sofreír la cebolla y el ajo en AOVE; añadir el pimentón y el chorizo, rehоgar 2 minutos.' },
      { paso: 'Incorporar las lentejas y cubrir con agua 3 cm por encima.' },
      { paso: 'Añadir el laurel; cocer a fuego medio 25 minutos.' },
      { paso: 'Ajustar sal y servir con un hilo de AOVE crudo.' },
    ],
    nota_food_mood_es: 'Las lentejas beluga tienen la mayor concentración de antocianinas entre las legumbres; el pimentón ahumado de la Vera contiene capsantina con efecto antiinflamatorio local; este plato de cuchara activa memorias de calor, raíz y seguridad que regulan el sistema límbico.',
    variantes_es: [{ variante: 'Versión vegana: sustituir el chorizo de pavo por pimentón extra y una cucharada de miso.' }],
    tags: ['confort', 'mediterráneo', 'lentejas', 'guiso', 'cena'],
  },
]

;(async () => {
  console.log(`🍽️  Iniciando seed de recetas mediterráneas (${RECETAS.length} recetas)...`)
  console.log('   Usando upsert — las recetas existentes no se borran.\n')

  let ok = 0
  let fail = 0

  for (const receta of RECETAS) {
    const { error } = await supabase
      .from('recetas')
      .upsert(receta, { onConflict: 'id' })

    if (error) {
      console.error(`  ❌ "${receta.nombre_es}" → ${error.message}`)
      fail++
    } else {
      console.log(`  ✅ ${receta.mood_es.split(' &')[0].padEnd(22)} · ${receta.nombre_es}`)
      ok++
    }
  }

  console.log(`\n✅ Completado: ${ok} insertadas / ${fail} errores`)
  process.exit(fail > 0 ? 1 : 0)
})()
