import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const RECIPES = [
  {
    id: 'comidista-sopa-miso-fideos-champinones',
    nombre_es: 'Sopa de miso con fideos y champiñones',
    mood_es: 'Calma & Tranquilidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 30, temporada: 'otoño-invierno',
    contexto_es: 'Receta de El Comidista. El miso aporta GABA y probióticos vivos que calman el sistema nervioso entérico. Los champiñones Portobello son ricos en betaglucanos inmunomoduladores.',
    ingredientes_es: [
      { ingrediente: '1,2 l de caldo de verduras' },
      { ingrediente: '1 puerro' },
      { ingrediente: '1 cebolla' },
      { ingrediente: '3 sobres de fideos udon' },
      { ingrediente: '300 g de champiñones Portobello' },
      { ingrediente: '80 g de cacahuetes tostados' },
      { ingrediente: '1 cucharada de miso blanco' },
      { ingrediente: '1 cucharada de sésamo' },
      { ingrediente: '1 chorro de salsa de soja' },
      { ingrediente: '200 g de tofu firme' },
      { ingrediente: 'Cilantro, cebollino, sriracha (opcionales)' },
    ],
    preparacion_es: [
      { paso: 'Sofríe puerro y cebolla en aceite hasta pochar.' },
      { paso: 'Añade los champiñones laminados y cocina 5 min.' },
      { paso: 'Agrega el caldo y lleva a ebullición.' },
      { paso: 'Incorpora los fideos udon y el tofu en dados.' },
      { paso: 'Fuera del fuego, disuelve el miso en un poco de caldo frío y añade a la sopa.' },
      { paso: 'Sirve con sésamo, cacahuetes, cilantro y sriracha al gusto.' },
    ],
    nota_food_mood_es: 'El miso debe añadirse fuera del fuego para conservar sus probióticos. GABA → calma neurológica. Betaglucanos → inmunidad.',
    variantes_es: [{ variante: 'Sin tofu: dobla los champiñones' }, { variante: 'Versión picante: más sriracha y jengibre rallado' }],
    tags: ['calma', 'miso', 'probióticos', 'sopa', 'reconfortante', 'comidista'],
  },
  {
    id: 'comidista-ramen-vagos-miso-jengibre-brocoli',
    nombre_es: 'Ramen para vagos con miso, jengibre y brócoli',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. El jengibre tiene potente efecto antiinflamatorio (gingeroles). La leche de coco aporta triglicéridos de cadena media para energía sostenida. El brócoli es rico en sulforafano neuroprotector.',
    ingredientes_es: [
      { ingrediente: '150 g de fideos para ramen' },
      { ingrediente: '800 ml de caldo de verduras' },
      { ingrediente: '100 ml de leche de coco' },
      { ingrediente: '2 cucharadas de crema de cacahuete' },
      { ingrediente: '1 cucharadita de miso' },
      { ingrediente: '1 trozo de jengibre fresco (2-3 cm)' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '4 cebolletas chinas' },
      { ingrediente: '1 cucharada de vinagre de arroz' },
      { ingrediente: '1 cucharada de salsa de soja' },
      { ingrediente: '1 cucharada de azúcar' },
      { ingrediente: 'Floretes de brócoli, huevo cocido, sésamo' },
    ],
    preparacion_es: [
      { paso: 'Mezcla en un bol la crema de cacahuete, miso, soja, vinagre, azúcar, ajo y jengibre rallado.' },
      { paso: 'Calienta el caldo y disuelve la mezcla anterior. Añade la leche de coco.' },
      { paso: 'Cuece los fideos según instrucciones del paquete.' },
      { paso: 'Blanquea el brócoli 2 min en agua hirviendo.' },
      { paso: 'Sirve el caldo sobre los fideos con brócoli, huevo partido y sésamo.' },
    ],
    nota_food_mood_es: 'Ramen antiinflamatorio express. Gingeroles del jengibre reducen prostaglandinas. MCT del coco → energía cerebral directa.',
    variantes_es: [{ variante: 'Añade tofu salteado para proteína vegetal' }, { variante: 'Pimentón ahumado en vez de sriracha' }],
    tags: ['energía', 'antiinflamatorio', 'ramen', 'jengibre', 'comidista'],
  },
  {
    id: 'comidista-sopa-miso-setas-huevos-marinados',
    nombre_es: 'Sopa de miso con setas y huevos marinados',
    mood_es: 'Calma & Tranquilidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'media',
    tiempo_preparacion_min: 40, temporada: 'otoño-invierno',
    contexto_es: 'Receta de El Comidista. Los shiitakes son fuente de eritadenina que reduce el colesterol y betaglucanos inmunomoduladores. El miso blanco aporta isoflavonas y probióticos vivos.',
    ingredientes_es: [
      { ingrediente: '4 huevos medianos' },
      { ingrediente: '50 ml de salsa de soja' },
      { ingrediente: '70 g de miso blanco' },
      { ingrediente: '1 lámina de alga nori' },
      { ingrediente: '200 g de shiitakes frescos' },
      { ingrediente: '200 g de gírgolas (seta ostra)' },
      { ingrediente: '100 g de shimeji blanco (o champiñones)' },
      { ingrediente: '1 cebolleta' },
      { ingrediente: '2 l de agua' },
      { ingrediente: '100 g de fideos de arroz' },
    ],
    preparacion_es: [
      { paso: 'Marina los huevos cocidos en soja diluida al 50% con agua durante 4h mínimo.' },
      { paso: 'Prepara un caldo ligero con agua, nori y setas 20 min.' },
      { paso: 'Saltea las setas aparte en sartén caliente.' },
      { paso: 'Disuelve el miso fuera del fuego en el caldo.' },
      { paso: 'Sirve con fideos, setas salteadas y huevo marinado partido.' },
    ],
    nota_food_mood_es: 'Sopa umami profundo. Miso fuera del fuego conserva Lactobacillus vivos. Shiitake → inmunomodulación. Nori → yodo para tiroides.',
    variantes_es: [{ variante: 'Añade tofu sedoso para proteína extra' }, { variante: 'Usa dashi de kombu y bonito en vez de agua' }],
    tags: ['calma', 'miso', 'setas', 'microbiota', 'probióticos', 'comidista'],
  },
  {
    id: 'comidista-ramen-umami-plant-based',
    nombre_es: 'Ramen umami plant-based (dashi kombu y miso rojo)',
    mood_es: 'Foco & Concentración',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 1, tipo_plato: 'almuerzo', dificultad: 'media',
    tiempo_preparacion_min: 60, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. El caldo dashi de kombu aporta ácido glutámico umami que activa receptores de glutamato en el hipocampo. El tahini proporciona tirosina precursora de dopamina. El miso rojo contiene más aminoácidos que el blanco.',
    ingredientes_es: [
      { ingrediente: '400 g de fideos para ramen' },
      { ingrediente: '8-10 shiitakes deshidratados' },
      { ingrediente: '20 g de alga kombu deshidratada' },
      { ingrediente: '1,5 l de agua' },
      { ingrediente: '90 g de crema de cacahuete' },
      { ingrediente: '110 g de tahini crudo' },
      { ingrediente: '90 g de miso rojo' },
      { ingrediente: '50 g de salsa de soja' },
      { ingrediente: '30 g de mirin' },
      { ingrediente: '15 g de azúcar moreno' },
      { ingrediente: 'Tofu, setas asadas, tomate asado, cebolla caramelizada' },
      { ingrediente: 'Alga nori, sésamo tostado' },
    ],
    preparacion_es: [
      { paso: 'Remoja kombu y shiitakes en agua fría 30 min. Lleva al fuego hasta casi hervir, retira.' },
      { paso: 'Mezcla tahini, crema de cacahuete, miso rojo, soja, mirin y azúcar para el taré.' },
      { paso: 'Cuece los fideos, escurre.' },
      { paso: 'Calienta el caldo dashi, añade 2-3 cucharadas de taré por bol.' },
      { paso: 'Sirve con toppings asados y nori.' },
    ],
    nota_food_mood_es: 'Glutamato del dashi activa circuitos de foco prefrontal. Tirosina del tahini → dopamina → motivación y concentración.',
    variantes_es: [{ variante: 'Añade doubanjiang para versión picante' }, { variante: 'Caldo de pollo si no es vegano' }],
    tags: ['foco', 'concentración', 'ramen', 'miso', 'plant-based', 'umami', 'comidista'],
  },
  {
    id: 'comidista-fermentar-vegetales-casa',
    nombre_es: 'Fermentar vegetales en casa: chucrut y zanahoria lactofermentada',
    mood_es: 'Reset & Limpieza',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'condimento', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: 'todo el año',
    contexto_es: 'Tutorial base de El Comidista. La fermentación láctica produce Lactobacillus y SCFA (ácidos grasos de cadena corta) que nutren el epitelio intestinal y modulan el eje intestino-cerebro. Base psicobiótica fundamental.',
    ingredientes_es: [
      { ingrediente: '1 kg de col blanca (para chucrut)' },
      { ingrediente: '15-20 g de sal sin yodo por kg de verdura' },
      { ingrediente: 'Semillas de mostaza, pimienta, hinojo, ajo al gusto' },
      { ingrediente: 'Para zanahoria: zanahorias + 20 g sal por litro de agua' },
      { ingrediente: 'Tarros de cristal con cierre hermético' },
    ],
    preparacion_es: [
      { paso: 'Ralla o corta finamente la col. Añade sal y amasa hasta que suelque líquido.' },
      { paso: 'Añade especias y compacta en tarro de cristal bien limpio.' },
      { paso: 'Sumerge completamente en su propio líquido. Cubre sin sellar del todo.' },
      { paso: 'Fermenta a temperatura ambiente 5-7 días, probando diariamente.' },
      { paso: 'Para zanahorias: prepara salmuera al 2%, sumerge, fermenta 3-5 días.' },
      { paso: 'Refrigera una vez alcanzado el sabor deseado.' },
    ],
    nota_food_mood_es: 'Psicobióticos en acción: Lactobacillus plantarum y L. brevis producen GABA directamente. Los SCFA nutren colonocitos y reducen permeabilidad intestinal.',
    variantes_es: [{ variante: 'Kimchi: añade pasta de guindilla, ajo y jengibre' }, { variante: 'Col lombarda fermentada: más antocianinas' }],
    tags: ['reset', 'microbiota', 'fermentados', 'psicobióticos', 'tutorial', 'comidista'],
  },
  {
    id: 'comidista-tartar-salmon-tailandes',
    nombre_es: 'Tartar de salmón al estilo tailandés',
    mood_es: 'Foco & Concentración',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'entrante', dificultad: 'media',
    tiempo_preparacion_min: 20, temporada: 'primavera-verano',
    contexto_es: 'Receta de El Comidista. El salmón crudo conserva intactos sus EPA y DHA que aumentan la fluidez de membranas neuronales, mejoran la transmisión sináptica y reducen neuroinflamación. El jengibre potencia la absorción.',
    ingredientes_es: [
      { ingrediente: '600 g de filete de salmón fresco (sin piel ni espinas, previamente congelado 48h)' },
      { ingrediente: '1 cebolleta grande' },
      { ingrediente: '2 limas (zumo)' },
      { ingrediente: '2 cucharadas de chutney de mango' },
      { ingrediente: '2 cucharadas de salsa de soja' },
      { ingrediente: '1 tacita de cacahuetes tostados pelados' },
      { ingrediente: '2 cucharadas de cilantro picado' },
      { ingrediente: '1 trozo de raíz de jengibre (rallado)' },
      { ingrediente: '1 cucharada de sésamo tostado' },
      { ingrediente: 'Sriracha al gusto' },
      { ingrediente: 'Tostadas o crackers para acompañar' },
    ],
    preparacion_es: [
      { paso: 'Corta el salmón a cuchillo en dados de 0,5 cm (nunca con picadora).' },
      { paso: 'Mezcla zumo de lima, soja, chutney, jengibre y sriracha.' },
      { paso: 'Incorpora el salmón y la cebolleta picada. Mezcla con suavidad.' },
      { paso: 'Refrigera 10 min. Sirve con cacahuetes, sésamo y cilantro por encima.' },
    ],
    nota_food_mood_es: 'DHA crudo sin oxidar → fluidez neuronal máxima. Congelar 48h a -20°C elimina parásitos. Jengibre → gingeroles anti-COX-2.',
    variantes_es: [{ variante: 'Servir en hojas de lechuga en vez de tostadas' }, { variante: 'Añadir aguacate en dados para más omega-9' }],
    tags: ['foco', 'omega-3', 'salmón', 'claridad mental', 'sin gluten', 'comidista'],
  },
  {
    id: 'comidista-risotto-caballa-espinacas-limon',
    nombre_es: 'Risotto de caballa y espinacas al limón',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'media',
    tiempo_preparacion_min: 40, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. La caballa es uno de los pescados más ricos en omega-3, vitamina D y B12. Las espinacas aportan folato para síntesis de serotonina. El limón maximiza la absorción del hierro no hemo.',
    ingredientes_es: [
      { ingrediente: '2 filetes de caballa a la plancha' },
      { ingrediente: '300 g de arroz arborio' },
      { ingrediente: '300 g de espinacas frescas' },
      { ingrediente: 'Caldo de pescado (aprox. 1 l)' },
      { ingrediente: '1 limón (zumo y ralladura)' },
      { ingrediente: '1 puerro' },
      { ingrediente: 'Queso parmesano al gusto' },
      { ingrediente: 'Aceite de oliva virgen extra, sal, pimienta' },
      { ingrediente: 'Perejil fresco' },
    ],
    preparacion_es: [
      { paso: 'Sofríe el puerro picado en aceite a fuego medio.' },
      { paso: 'Añade el arroz y nácaralo 2 min.' },
      { paso: 'Ve añadiendo caldo caliente cazo a cazo, removiendo constantemente.' },
      { paso: 'A mitad de cocción incorpora las espinacas.' },
      { paso: 'Fuera del fuego, añade parmesano, ralladura de limón y mantequilla.' },
      { paso: 'Sirve con caballa desmenuzada, zumo de limón y perejil.' },
    ],
    nota_food_mood_es: 'Vitamina D de la caballa → síntesis de serotonina y dopamina. Folato de espinacas → metilación del DNA y estado de ánimo. Vitamina C del limón triplica absorción del hierro.',
    variantes_es: [{ variante: 'Sustituye caballa por salmón o boquerones frescos' }, { variante: 'Versión sin gluten: usa arroz carnaroli' }],
    tags: ['energía', 'omega-3', 'caballa', 'vitalidad', 'risotto', 'comidista'],
  },
  {
    id: 'comidista-pasta-sardinas-pinones',
    nombre_es: 'Pasta con sardinas y piñones',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 15, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. Las sardinillas en aceite de oliva conservan intactos sus omega-3. Son la fuente de calcio más biodisponible junto con los lácteos. Los piñones aportan zinc para la síntesis de neurotransmisores.',
    ingredientes_es: [
      { ingrediente: '200 g de pasta (espaguetis o linguini)' },
      { ingrediente: '1 lata de sardinillas en aceite de oliva' },
      { ingrediente: '50 g de piñones' },
      { ingrediente: 'Perejil fresco' },
      { ingrediente: 'Ajo al gusto' },
      { ingrediente: 'Aceite de oliva virgen extra, sal' },
    ],
    preparacion_es: [
      { paso: 'Cuece la pasta al dente en agua con sal.' },
      { paso: 'Tuesta los piñones en sartén seca hasta dorar.' },
      { paso: 'En la misma sartén, sofríe ajo laminado en aceite.' },
      { paso: 'Añade las sardinas desmenuzadas con su aceite.' },
      { paso: 'Incorpora la pasta escurrida, piñones y perejil. Mezcla.' },
    ],
    nota_food_mood_es: 'Omega-3 EPA+DHA de sardina → reducción de inflamación neurológica. Calcio biodisponible de las espinas. Zinc de piñones → cofactor de más de 100 enzimas.',
    variantes_es: [{ variante: 'Añade ralladura de limón y alcaparras al final' }, { variante: 'Usa pasta integral para más fibra prebiótica' }],
    tags: ['energía', 'omega-3', 'sardinas', 'rápido', 'comidista'],
  },
  {
    id: 'comidista-bocadillo-arenque-encurtido',
    nombre_es: 'Bocadillo de arenque encurtido al estilo alemán',
    mood_es: 'Reset & Limpieza',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 15, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. El arenque encurtido combina omega-3 con probióticos del encurtido. El pan de centeno aporta fibra de beta-glucano. Ideal para el mercado germanohablante.',
    ingredientes_es: [
      { ingrediente: '4 filetes de arenque encurtido (o salmón ahumado)' },
      { ingrediente: '2 panecillos (o pan de centeno)' },
      { ingrediente: '2 hojas de lechuga rizada' },
      { ingrediente: '½ cebolla roja' },
      { ingrediente: '150 g de mayonesa' },
      { ingrediente: '1 cucharadita de mostaza Dijon' },
      { ingrediente: '1 cucharada de alcaparras' },
      { ingrediente: '1 cucharada de pepinillos encurtidos picados' },
      { ingrediente: '2 filetes de anchoa' },
      { ingrediente: 'Perejil fresco, ralladura de limón' },
    ],
    preparacion_es: [
      { paso: 'Prepara la remoulade: mezcla mayonesa, mostaza, alcaparras, pepinillos, anchoa picada, perejil y ralladura de limón.' },
      { paso: 'Tuesta ligeramente el pan.' },
      { paso: 'Unta la remoulade en ambas mitades.' },
      { paso: 'Coloca lechuga, cebolla roja en aros finos y el arenque.' },
    ],
    nota_food_mood_es: 'Arenque: omega-3 + histamina reducida (encurtido estabiliza). Probióticos del pepinillo y alcaparras. Pan de centeno: betaglucanos → microbiota.',
    variantes_es: [{ variante: 'Usa salmón ahumado para sabor más suave' }, { variante: 'Pan de centeno integral para más fibra' }],
    tags: ['reset', 'omega-3', 'arenque', 'microbiota', 'comidista'],
  },
  {
    id: 'comidista-hummus-extrafino-garbanzos-tahini',
    nombre_es: 'Hummus extrafino de garbanzos con tahini',
    mood_es: 'Calma & Tranquilidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'entrante', dificultad: 'fácil',
    tiempo_preparacion_min: 15, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. Los garbanzos son la fuente vegetal más rica en triptófano, precursor de serotonina. El tahini aporta calcio y tirosina. Juntos crean una combinación aminoacídica óptima para calma sostenida.',
    ingredientes_es: [
      { ingrediente: '400 g de garbanzos cocidos (bote)' },
      { ingrediente: '½ cucharadita de comino en grano' },
      { ingrediente: '120-150 g de tahini' },
      { ingrediente: '1 diente de ajo' },
      { ingrediente: '1,5 cucharadas de zumo de limón' },
      { ingrediente: 'Sal al gusto' },
      { ingrediente: 'Cubitos de hielo (para textura sedosa)' },
      { ingrediente: 'AOVE y pimentón para servir' },
    ],
    preparacion_es: [
      { paso: 'Tuesta el comino en sartén seca 1 min.' },
      { paso: 'Tritura garbanzos, tahini, ajo, limón, comino y sal con varios cubitos de hielo.' },
      { paso: 'Procesa 4-5 min hasta obtener textura muy cremosa.' },
      { paso: 'Sirve con un hilo de AOVE y pimentón.' },
    ],
    nota_food_mood_es: 'El hielo crea emulsión perfecta con el tahini. Triptófano de garbanzos → 5-HTP → serotonina. Tahini: calcio + tirosina → calma y equilibrio.',
    variantes_es: [{ variante: 'Añade remolacha cocida para hummus rosa' }, { variante: 'Con ajo asado en vez de crudo para sabor más dulce' }],
    tags: ['calma', 'serotonina', 'triptófano', 'garbanzos', 'hummus', 'vegano', 'comidista'],
  },
  {
    id: 'comidista-hummus-judia-blanca-setas',
    nombre_es: 'Hummus de judía blanca con setas salteadas',
    mood_es: 'Confort & Placer',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'entrante', dificultad: 'media',
    tiempo_preparacion_min: 25, temporada: 'otoño-invierno',
    contexto_es: 'Receta de El Comidista. Las judías blancas tienen índice glucémico bajo y alta densidad de fibra prebiótica. Los piñones aportan zinc y magnesio. Las setas Portobello contienen ergotioneína antioxidante única.',
    ingredientes_es: [
      { ingrediente: '250 g de judía blanca del ganxet seca (o 500 g cocida)' },
      { ingrediente: '150 g de tahini' },
      { ingrediente: 'Zumo de 1 limón' },
      { ingrediente: '1 diente de ajo' },
      { ingrediente: '100 ml de agua helada' },
      { ingrediente: '200 g de setas (portobello, gírgolas, champiñón)' },
      { ingrediente: '50 g de piñones' },
      { ingrediente: 'Sal, pimienta, comino, orégano, perejil fresco' },
    ],
    preparacion_es: [
      { paso: 'Si usas judías secas, remoja 12h y cuece 1,5h.' },
      { paso: 'Tritura judías con tahini, ajo, limón y agua helada hasta que sea sedoso.' },
      { paso: 'Saltea las setas a fuego muy alto sin mover hasta que doren.' },
      { paso: 'Tuesta los piñones en sartén seca.' },
      { paso: 'Sirve el hummus con setas, piñones, hierbas y un hilo de aceite.' },
    ],
    nota_food_mood_es: 'Fibra soluble de judías → Bifidobacterias. Ergotioneína de setas → antioxidante específico de células nerviosas. Magnesio de piñones → relajación muscular.',
    variantes_es: [{ variante: 'Con garbanzos si no encuentras judías ganxet' }, { variante: 'Añade aceite de trufa para versión más lujosa' }],
    tags: ['confort', 'legumbres', 'setas', 'microbiota', 'reconfortante', 'comidista'],
  },
  {
    id: 'comidista-espinacas-catalana-garbanzos-pinones',
    nombre_es: 'Espinacas a la catalana con garbanzos, piñones y pasas',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'mujer', grupo_edad: '30-60',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. Las espinacas son la fuente vegetal más rica en folato, esencial para la síntesis de serotonina y dopamina. El hierro no hemo se absorbe mejor con vitamina C (vinagre). Los garbanzos aportan triptófano.',
    ingredientes_es: [
      { ingrediente: '300 g de espinacas baby' },
      { ingrediente: '800 g de garbanzos cocidos' },
      { ingrediente: '2 dientes de ajo' },
      { ingrediente: '2 cucharadas de piñones tostados' },
      { ingrediente: '2-3 cucharadas de pasas sultanas' },
      { ingrediente: 'Aceite de oliva virgen extra' },
      { ingrediente: 'Vinagre de Jerez, sal, pimienta' },
    ],
    preparacion_es: [
      { paso: 'Tuesta los piñones en sartén seca hasta dorar. Reserva.' },
      { paso: 'Sofríe el ajo laminado en aceite hasta dorar.' },
      { paso: 'Añade las pasas, los garbanzos y sofríe 3 min.' },
      { paso: 'Incorpora las espinacas, saltea hasta que reduzcan.' },
      { paso: 'Añade un chorro de vinagre de Jerez. Sirve con piñones.' },
    ],
    nota_food_mood_es: 'Receta clásica catalana con perfil funcional excepcional. Folato + hierro + triptófano = triángulo de la serotonina. El vinagre mejora la absorción del hierro.',
    variantes_es: [{ variante: 'Con uvas pasas y almendras en lugar de piñones' }, { variante: 'Añade anchoas para sabor umami y omega-3' }],
    tags: ['energía', 'hierro', 'folato', 'serotonina', 'mujer', 'espinacas', 'comidista'],
  },
  {
    id: 'comidista-ensalada-lentejas-remolacha-nueces',
    nombre_es: 'Ensalada de lentejas con remolacha, manzana y nueces',
    mood_es: 'Reset & Limpieza',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 15, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. Las lentejas son la legumbre con mayor concentración de fibra prebiótica. La remolacha contiene betaína que protege el hígado y nitratos que mejoran el flujo sanguíneo cerebral. Las nueces son la nuez más rica en ALA.',
    ingredientes_es: [
      { ingrediente: '1 kg de lentejas cocidas' },
      { ingrediente: '500 g de remolachas cocidas' },
      { ingrediente: '2 manzanas' },
      { ingrediente: '1 cebolla roja' },
      { ingrediente: '100 g de nueces' },
      { ingrediente: '50 g de pasas' },
      { ingrediente: '50 g de aceitunas' },
      { ingrediente: 'Queso al gusto (feta, manchego)' },
      { ingrediente: 'Aceite de oliva virgen extra, vinagre, sal, pimienta' },
    ],
    preparacion_es: [
      { paso: 'Corta la remolacha en dados y la manzana en láminas finas.' },
      { paso: 'Pica la cebolla roja muy fina.' },
      { paso: 'Mezcla lentejas, remolacha, manzana, cebolla, pasas y aceitunas.' },
      { paso: 'Aliña con aceite, vinagre, sal y pimienta.' },
      { paso: 'Sirve con nueces rotas y queso desmenuzado.' },
    ],
    nota_food_mood_es: 'Remolacha: nitratos → óxido nítrico → vasodilatación cerebral → claridad. Lenteja: fibra prebiótica + folato. Nuez: ALA → reducción inflamación.',
    variantes_es: [{ variante: 'Añade aguacate para más grasas saludables' }, { variante: 'Versión vegana: quita el queso, añade semillas de calabaza' }],
    tags: ['reset', 'reequilibrio', 'lentejas', 'remolacha', 'detox suave', 'comidista'],
  },
  {
    id: 'comidista-guacamole-clasico-variantes',
    nombre_es: 'Guacamole clásico y sus variantes creativas',
    mood_es: 'Foco & Concentración',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'entrante', dificultad: 'fácil',
    tiempo_preparacion_min: 10, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. El aguacate es una de las mejores fuentes de ácido oleico (omega-9) que mejora la plasticidad de las membranas neuronales. La luteína del aguacate se acumula en el córtex visual y prefrontal mejorando función cognitiva.',
    ingredientes_es: [
      { ingrediente: '2 aguacates maduros' },
      { ingrediente: 'Zumo de 1 lima' },
      { ingrediente: '½ cebolla roja picada' },
      { ingrediente: '2 cucharadas de cilantro fresco' },
      { ingrediente: '1 tomate' },
      { ingrediente: '1 chile serrano (o jalapeño)' },
      { ingrediente: '1 cucharada de aceite de oliva virgen extra' },
      { ingrediente: 'Sal, pimienta' },
    ],
    preparacion_es: [
      { paso: 'Aplasta el aguacate con un tenedor (no en batidora, para mantener textura).' },
      { paso: 'Añade lima inmediatamente para evitar oxidación.' },
      { paso: 'Incorpora cebolla, cilantro, tomate en dados y chile.' },
      { paso: 'Ajusta sal. Sirve inmediatamente o cubre con film a piel para conservar.' },
    ],
    nota_food_mood_es: 'Omega-9 del aguacate → fluidez de membrana neuronal. Luteína → acumulación en córtex prefrontal → función ejecutiva. Vitamina K2 → salud neurológica.',
    variantes_es: [
      { variante: 'Con semillas de granada: +polifenoles antioxidantes' },
      { variante: 'Con mango: +vitamina A y dulzor antiinflamatorio' },
      { variante: 'Con edamame: +proteína vegetal completa' },
    ],
    tags: ['foco', 'aguacate', 'omega-9', 'neuroprotector', 'vegano', 'rápido', 'comidista'],
  },
  {
    id: 'comidista-ensaladas-otono-boniato-alubias',
    nombre_es: 'Ensaladas de otoño: boniato asado, alubias negras y aguacate',
    mood_es: 'Social & Conexión',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'almuerzo', dificultad: 'fácil',
    tiempo_preparacion_min: 35, temporada: 'otoño-invierno',
    contexto_es: 'Receta de El Comidista. El boniato tiene índice glucémico moderado (menor que la patata) y es rico en betacarotenos y vitamina B6 (precursor de serotonina). Las alubias negras contienen antocianinas neuroprotectoras.',
    ingredientes_es: [
      { ingrediente: '1 boniato grande en dados' },
      { ingrediente: '200 g de alubias negras cocidas' },
      { ingrediente: '½ cebolla morada' },
      { ingrediente: '1 aguacate' },
      { ingrediente: 'Lechuga variada' },
      { ingrediente: '1 manzana' },
      { ingrediente: '100 g de nueces pecanas' },
      { ingrediente: 'Zumo de lima + chile + aceite de oliva (vinagreta)' },
      { ingrediente: 'Vinagre de Jerez, sal, pimienta' },
    ],
    preparacion_es: [
      { paso: 'Asa el boniato en dados a 200°C con aceite y sal, 25 min.' },
      { paso: 'Prepara vinagreta de lima, aceite, chile y sal.' },
      { paso: 'Mezcla lechuga, alubias, manzana en láminas y cebolla roja.' },
      { paso: 'Añade el boniato asado caliente.' },
      { paso: 'Corona con aguacate en dados, nueces pecanas y vinagreta.' },
    ],
    nota_food_mood_es: 'B6 del boniato → 5-HTP → serotonina. Antocianinas de alubia negra → neuroprotección. Estas ensaladas son ideales para comer en compañía.',
    variantes_es: [{ variante: 'Con pollo a la plancha para proteína completa' }, { variante: 'Versión vegana: usa semillas de cáñamo' }],
    tags: ['social', 'boniato', 'alubias', 'otoño', 'colorida', 'comidista'],
  },
  {
    id: 'comidista-boles-desayuno-avena-platano-cacao',
    nombre_es: 'Boles de desayuno: gachas de avena con plátano, cacahuete y chocolate',
    mood_es: 'Activación & Energía',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'desayuno', dificultad: 'fácil',
    tiempo_preparacion_min: 10, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. La avena tiene beta-glucano que regula glucemia matinal. El plátano maduro aporta triptófano y potasio. El cacao 70%+ contiene teobromina y feniletilamina que elevan el estado de ánimo.',
    ingredientes_es: [
      { ingrediente: '400 ml de leche (o bebida vegetal)' },
      { ingrediente: '8 cucharadas de copos de avena integrales' },
      { ingrediente: '2 plátanos maduros' },
      { ingrediente: '2 cucharaditas de mantequilla de cacahuete' },
      { ingrediente: 'Cacahuetes picados' },
      { ingrediente: 'Arándanos frescos' },
      { ingrediente: 'Chocolate 70% o pepitas de cacao' },
      { ingrediente: 'Canela, AOVE, sal' },
    ],
    preparacion_es: [
      { paso: 'Calienta la leche y añade los copos de avena.' },
      { paso: 'Cocina 5 min removiendo hasta obtener la textura deseada.' },
      { paso: 'Aplasta medio plátano dentro de las gachas para endulzar sin azúcar.' },
      { paso: 'Sirve en bol con el resto del plátano en rodajas, mantequilla de cacahuete, arándanos, cacao y cacahuetes.' },
    ],
    nota_food_mood_es: 'Beta-glucano → pico glucémico suave → energía sostenida 4h. Plátano: triptófano+potasio → serotonina matinal. Cacao: feniletilamina → buen humor sin estimulación excesiva.',
    variantes_es: [{ variante: 'Overnight oats: prepara la noche anterior en frío' }, { variante: 'Añade semillas de chía para omega-3 vegetal' }],
    tags: ['energía', 'desayuno', 'avena', 'serotonina', 'plátano', 'comidista'],
  },
  {
    id: 'comidista-crema-boniato-coco-jengibre',
    nombre_es: 'Crema de boniato y coco con jengibre',
    mood_es: 'Calma & Tranquilidad',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 35, temporada: 'otoño-invierno',
    contexto_es: 'Receta de El Comidista. El boniato es rico en vitamina B6 y magnesio. La leche de coco aporta MCT. El jengibre fresco contiene gingeroles y shogaoles con potente efecto antiinflamatorio y calmante digestivo.',
    ingredientes_es: [
      { ingrediente: '800 g de boniatos' },
      { ingrediente: '1 litro de caldo de verduras' },
      { ingrediente: '400 ml de leche de coco' },
      { ingrediente: '1 cucharada de jengibre fresco rallado' },
      { ingrediente: '1 cucharadita de comino' },
      { ingrediente: '1 guindilla o chile rojo' },
      { ingrediente: '1 cucharada de azúcar moreno' },
      { ingrediente: '1 lima (zumo)' },
      { ingrediente: 'Cilantro, aceite de oliva, sal' },
    ],
    preparacion_es: [
      { paso: 'Pela y trocea los boniatos. Sofríe con jengibre, comino y guindilla 5 min.' },
      { paso: 'Añade el caldo y cuece hasta que el boniato esté tierno (20 min).' },
      { paso: 'Tritura hasta obtener crema fina.' },
      { paso: 'Incorpora la leche de coco y el azúcar. Ajusta sal.' },
      { paso: 'Sirve con zumo de lima, cilantro y un hilo de aceite.' },
    ],
    nota_food_mood_es: 'Triángulo antiestrés: B6 (boniato) + MCT (coco) + gingeroles (jengibre). El jengibre reduce cortisol y calma el sistema nervioso entérico.',
    variantes_es: [{ variante: 'Añade cúrcuma para potenciar el efecto antiinflamatorio' }, { variante: 'Con curry en polvo para versión más aromática' }],
    tags: ['calma', 'antiinflamatorio', 'boniato', 'jengibre', 'reconfortante', 'comidista'],
  },
  {
    id: 'comidista-crema-alubias-negras-mexicana',
    nombre_es: 'Crema rápida de alubias negras tipo mexicana',
    mood_es: 'Confort & Placer',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. Las alubias negras son la legumbre más rica en antocianinas, pigmentos neuroprotectores que reducen el estrés oxidativo cerebral. Tienen además fibra prebiótica de alto impacto en Bifidobacterias.',
    ingredientes_es: [
      { ingrediente: '400 g de alubias negras cocidas' },
      { ingrediente: '600 ml de caldo de pollo o verduras' },
      { ingrediente: '1 cebolla' },
      { ingrediente: '1 zanahoria' },
      { ingrediente: '1 guindilla' },
      { ingrediente: '1 cucharadita de comino' },
      { ingrediente: '1 lima (zumo)' },
      { ingrediente: '1 aguacate (para servir)' },
      { ingrediente: '1 tomate picado' },
      { ingrediente: 'Aceite de oliva virgen extra, sal' },
    ],
    preparacion_es: [
      { paso: 'Sofríe cebolla y zanahoria picadas 5 min en aceite.' },
      { paso: 'Añade guindilla y comino, sofríe 1 min más.' },
      { paso: 'Incorpora las alubias y el caldo. Cuece 10 min.' },
      { paso: 'Tritura parcialmente: deja algunas alubias enteras para textura.' },
      { paso: 'Sirve con lima, aguacate en dados y tomate fresco.' },
    ],
    nota_food_mood_es: 'Antocianinas de alubia negra → reducen estrés oxidativo cerebral un 40%. Fibra prebiótica → Bifidobacterias → producción de GABA y serotonina intestinal.',
    variantes_es: [{ variante: 'Añade chorizo o bacon para versión más sabrosa' }, { variante: 'Con nata agria y cilantro para versión tex-mex' }],
    tags: ['confort', 'alubias', 'antocianinas', 'microbiota', 'reconfortante', 'comidista'],
  },
  {
    id: 'comidista-sopa-verduras-invierno-fideos-integrales',
    nombre_es: 'Sopa de verduras de invierno con fideos integrales y huevo',
    mood_es: 'Reset & Limpieza',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'cena', dificultad: 'fácil',
    tiempo_preparacion_min: 30, temporada: 'otoño-invierno',
    contexto_es: 'Receta de El Comidista. El nabo contiene glucosinolatos que activan vías de detoxificación hepática. Las espinacas aportan folato. Los fideos integrales tienen fibra fermentable. El huevo pochado añade colina para síntesis de acetilcolina.',
    ingredientes_es: [
      { ingrediente: '4 zanahorias grandes' },
      { ingrediente: '2 puerros' },
      { ingrediente: '1 nabo mediano' },
      { ingrediente: '300 g de espinacas frescas' },
      { ingrediente: '200 g de fideos integrales' },
      { ingrediente: '8 huevos' },
      { ingrediente: '2 l de caldo de pollo o verduras' },
      { ingrediente: 'AOVE, sal, pimienta, limón' },
    ],
    preparacion_es: [
      { paso: 'Trocea zanahoria, puerro y nabo. Sofríe en aceite 5 min.' },
      { paso: 'Añade el caldo y cuece 15 min.' },
      { paso: 'Incorpora los fideos y cuece el tiempo indicado.' },
      { paso: 'Añade las espinacas 2 min antes de acabar.' },
      { paso: 'Pocha los huevos aparte en agua con vinagre.' },
      { paso: 'Sirve la sopa con un huevo por bol, zumo de limón y aceite.' },
    ],
    nota_food_mood_es: 'Sopa de reset postnavideño o post-exceso. Nabo: glucosinolatos → detox hepático. Huevo: colina → acetilcolina → claridad mental. Espinacas: folato → síntesis de serotonina.',
    variantes_es: [{ variante: 'Añade miso al final para versión probiótica' }, { variante: 'Con garbanzos en vez de huevo para versión vegana' }],
    tags: ['reset', 'detox', 'depurativo', 'invierno', 'verduras', 'comidista'],
  },
  {
    id: 'comidista-tortitas-platano-avena-chia',
    nombre_es: 'Tortitas de plátano y avena con semillas de chía',
    mood_es: 'Confort & Placer',
    segmento: 'adulto', sexo: 'unisex', grupo_edad: 'todas',
    premium_level: 0, tipo_plato: 'desayuno', dificultad: 'fácil',
    tiempo_preparacion_min: 20, temporada: 'todo el año',
    contexto_es: 'Receta de El Comidista. Estas tortitas combinan tres fuentes de triptófano (plátano, avena, chía). Sin gluten ni lactosa en su versión base. Las semillas de chía aportan ALA omega-3 vegetal y fibra soluble que forma gel prebiótico.',
    ingredientes_es: [
      { ingrediente: '3 plátanos grandes maduros' },
      { ingrediente: '75 g de copos de avena integrales' },
      { ingrediente: '200 ml de leche o bebida vegetal' },
      { ingrediente: '1 cucharada de semillas de chía' },
      { ingrediente: '13 g de impulsor (levadura Royal)' },
      { ingrediente: 'Aceite neutro para la sartén' },
      { ingrediente: 'Toppings: arándanos, cacao, miel, frutos rojos' },
    ],
    preparacion_es: [
      { paso: 'Hidrata la chía en la leche 5 min.' },
      { paso: 'Tritura plátanos con la leche y chía.' },
      { paso: 'Incorpora la avena y el impulsor. Mezcla.' },
      { paso: 'Cocina cucharadas de masa en sartén antiadherente con poco aceite, 2 min por lado.' },
      { paso: 'Sirve con toppings al gusto.' },
    ],
    nota_food_mood_es: 'Triple triptófano: plátano + avena + chía → serotonina para el fin de semana. ALA de chía → conversión parcial a EPA. Sin azúcar añadida: endulzado solo con plátano maduro.',
    variantes_es: [
      { variante: 'Con mantequilla de cacahuete: +triptófano y proteína' },
      { variante: 'Versión salada: quita el impulsor, añade queso y hierbas' },
    ],
    tags: ['confort', 'desayuno', 'plátano', 'avena', 'triptófano', 'sin gluten', 'comidista'],
  },
];

async function main() {
  console.log(`Insertando ${RECIPES.length} recetas de El Comidista...`);

  const { data, error } = await supabase
    .from('recetas')
    .upsert(RECIPES, { onConflict: 'id' });

  if (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }

  console.log(`✅ ${RECIPES.length} recetas insertadas/actualizadas correctamente.`);
}

main();
